import { AxiosProxyConfig } from 'axios';

export interface Config {
  userAgent?: string;
  timeout?: number;
  proxy?: AxiosProxyConfig;
}

export interface ItemDetails {
  id: number;
  name: string;
  description: string;
  icon: string;
  members?: boolean;
}

export interface ItemPrice {
  current: number;
  change: {
    today: number;
    day30: number;
    day90: number;
    day180: number;
  };
}

export interface Item extends ItemDetails {
  price: ItemPrice;
}

export interface ApiItemDetails {
  id: number;
  name: string;
  description: string;
  icon_large: string;
  members: string;
}

export interface ApiItemPage {
  total: number;
  items: ApiItemDetails[];
}

export interface JsonItem {
  [key: string]: number;
}

export interface ItemPriceGraph {
  daily: { [key: string]: number };
  average: { [key: string]: number };
}

export type ItemName =
  | 'a powdered wig'
  | 'abyssal bludgeon'
  | 'abyssal bracelet(5)'
  | 'abyssal dagger'
  | 'abyssal dagger (p)'
  | 'abyssal dagger (p+)'
  | 'abyssal dagger (p++)'
  | 'abyssal whip'
  | 'achey tree logs'
  | 'acorn'
  | 'adamant 2h sword'
  | 'adamant arrow'
  | 'adamant arrow(p)'
  | 'adamant arrow(p+)'
  | 'adamant arrow(p++)'
  | 'adamant arrowtips'
  | 'adamant axe'
  | 'adamant battleaxe'
  | 'adamant bolts'
  | 'adamant bolts (p)'
  | 'adamant bolts (p+)'
  | 'adamant bolts (p++)'
  | 'adamant bolts(unf)'
  | 'adamant boots'
  | 'adamant brutal'
  | 'adamant cane'
  | 'adamant chainbody'
  | 'adamant claws'
  | 'adamant crossbow'
  | 'adamant crossbow (u)'
  | 'adamant dagger'
  | 'adamant dagger(p)'
  | 'adamant dagger(p+)'
  | 'adamant dagger(p++)'
  | 'adamant dart'
  | 'adamant dart tip'
  | 'adamant dart(p)'
  | 'adamant dart(p+)'
  | 'adamant dart(p++)'
  | 'adamant dragon mask'
  | 'adamant full helm'
  | 'adamant full helm (g)'
  | 'adamant full helm (t)'
  | 'adamant gold-trimmed set (lg)'
  | 'adamant gold-trimmed set (sk)'
  | 'adamant halberd'
  | 'adamant hasta'
  | 'adamant hasta(p)'
  | 'adamant hasta(p+)'
  | 'adamant hasta(p++)'
  | 'adamant helm (h1)'
  | 'adamant helm (h2)'
  | 'adamant helm (h3)'
  | 'adamant helm (h4)'
  | 'adamant helm (h5)'
  | 'adamant javelin'
  | 'adamant javelin heads'
  | 'adamant javelin(p)'
  | 'adamant javelin(p+)'
  | 'adamant javelin(p++)'
  | 'adamant kiteshield'
  | 'adamant kiteshield (g)'
  | 'adamant kiteshield (t)'
  | 'adamant knife'
  | 'adamant knife(p)'
  | 'adamant knife(p+)'
  | 'adamant knife(p++)'
  | 'adamant longsword'
  | 'adamant mace'
  | 'adamant med helm'
  | 'adamant pickaxe'
  | 'adamant platebody'
  | 'adamant platebody (g)'
  | 'adamant platebody (h1)'
  | 'adamant platebody (h2)'
  | 'adamant platebody (h3)'
  | 'adamant platebody (h4)'
  | 'adamant platebody (h5)'
  | 'adamant platebody (t)'
  | 'adamant platelegs'
  | 'adamant platelegs (g)'
  | 'adamant platelegs (t)'
  | 'adamant plateskirt'
  | 'adamant plateskirt (g)'
  | 'adamant plateskirt (t)'
  | 'adamant scimitar'
  | 'adamant set (lg)'
  | 'adamant set (sk)'
  | 'adamant shield (h1)'
  | 'adamant shield (h2)'
  | 'adamant shield (h3)'
  | 'adamant shield (h4)'
  | 'adamant shield (h5)'
  | 'adamant spear'
  | 'adamant spear(p)'
  | 'adamant spear(p+)'
  | 'adamant spear(p++)'
  | 'adamant sq shield'
  | 'adamant sword'
  | 'adamant thrownaxe'
  | 'adamant trimmed set (lg)'
  | 'adamant trimmed set (sk)'
  | 'adamant warhammer'
  | 'adamantite bar'
  | 'adamantite limbs'
  | 'adamantite nails'
  | 'adamantite ore'
  | 'admiral pie'
  | 'afro'
  | 'agility mix(1)'
  | 'agility mix(2)'
  | 'agility potion(1)'
  | 'agility potion(2)'
  | 'agility potion(3)'
  | 'agility potion(4)'
  | "ahrim's armour set"
  | "ahrim's hood"
  | "ahrim's hood 0"
  | "ahrim's robeskirt"
  | "ahrim's robeskirt 0"
  | "ahrim's robetop"
  | "ahrim's robetop 0"
  | "ahrim's staff"
  | "ahrim's staff 0"
  | 'air battlestaff'
  | 'air orb'
  | 'air rune'
  | 'air talisman'
  | 'air tiara'
  | 'airtight pot'
  | 'ale of the gods'
  | 'ale yeast'
  | 'amethyst'
  | 'amethyst arrow'
  | 'amethyst arrow(p)'
  | 'amethyst arrow(p+)'
  | 'amethyst arrow(p++)'
  | 'amethyst arrowtips'
  | 'amethyst bolt tips'
  | 'amethyst broad bolts'
  | 'amethyst javelin'
  | 'amethyst javelin heads'
  | 'amethyst javelin(p)'
  | 'amethyst javelin(p+)'
  | 'amethyst javelin(p++)'
  | 'amulet mould'
  | 'amulet of accuracy'
  | 'amulet of avarice'
  | 'amulet of bounty'
  | 'amulet of chemistry'
  | 'amulet of defence'
  | 'amulet of defence (t)'
  | 'amulet of eternal glory'
  | 'amulet of fury'
  | 'amulet of glory'
  | 'amulet of glory (t)'
  | 'amulet of glory (t4)'
  | 'amulet of glory (t6)'
  | 'amulet of glory(4)'
  | 'amulet of glory(6)'
  | 'amulet of magic'
  | 'amulet of magic (t)'
  | 'amulet of power'
  | 'amulet of power (t)'
  | 'amulet of strength'
  | 'amulet of the damned (full)'
  | 'amulet of torture'
  | 'amylase crystal'
  | 'ancestral hat'
  | 'ancestral robe bottom'
  | 'ancestral robe top'
  | 'ancestral robes set'
  | 'anchovies'
  | 'anchovy pizza'
  | 'ancient blessing'
  | 'ancient bracers'
  | 'ancient chaps'
  | 'ancient cloak'
  | 'ancient coif'
  | 'ancient crozier'
  | 'ancient crystal'
  | "ancient d'hide"
  | "ancient d'hide boots"
  | "ancient d'hide shield"
  | 'ancient dragonhide set'
  | 'ancient effigy'
  | 'ancient emblem'
  | 'ancient full helm'
  | 'ancient kiteshield'
  | 'ancient mace'
  | 'ancient medallion'
  | 'ancient mitre'
  | 'ancient page 1'
  | 'ancient page 2'
  | 'ancient page 3'
  | 'ancient page 4'
  | 'ancient platebody'
  | 'ancient platelegs'
  | 'ancient plateskirt'
  | 'ancient relic'
  | 'ancient robe legs'
  | 'ancient robe top'
  | 'ancient rune armour set (lg)'
  | 'ancient rune armour set (sk)'
  | 'ancient staff'
  | 'ancient statuette'
  | 'ancient stole'
  | 'ancient totem'
  | 'ancient wyvern shield'
  | 'anglerfish'
  | 'anguish ornament kit'
  | 'ankou gloves'
  | 'ankou leggings'
  | 'ankou mask'
  | 'ankou socks'
  | 'ankou top'
  | 'annakarl teleport'
  | 'anti-dragon shield'
  | 'anti-poison supermix(1)'
  | 'anti-poison supermix(2)'
  | 'anti-venom(1)'
  | 'anti-venom(2)'
  | 'anti-venom(3)'
  | 'anti-venom(4)'
  | 'anti-venom+(1)'
  | 'anti-venom+(2)'
  | 'anti-venom+(3)'
  | 'anti-venom+(4)'
  | 'antidote+ mix(1)'
  | 'antidote+ mix(2)'
  | 'antidote+(1)'
  | 'antidote+(2)'
  | 'antidote+(3)'
  | 'antidote+(4)'
  | 'antidote++(1)'
  | 'antidote++(2)'
  | 'antidote++(3)'
  | 'antidote++(4)'
  | 'antifire mix(1)'
  | 'antifire mix(2)'
  | 'antifire potion(1)'
  | 'antifire potion(2)'
  | 'antifire potion(3)'
  | 'antifire potion(4)'
  | 'antipoison mix(1)'
  | 'antipoison mix(2)'
  | 'antipoison(1)'
  | 'antipoison(2)'
  | 'antipoison(3)'
  | 'antipoison(4)'
  | 'ape atoll teleport'
  | 'apple mush'
  | 'apple pie'
  | 'apple sapling'
  | 'apple tree seed'
  | 'apples(5)'
  | 'apprentice wand'
  | 'arcane prayer scroll'
  | 'arcane sigil'
  | 'arcane spirit shield'
  | 'arceuus banner'
  | 'arceuus hood'
  | 'arceuus scarf'
  | 'archer helm'
  | 'archers ring'
  | 'archery ticket'
  | 'arctic pine logs'
  | 'arctic pyre logs'
  | 'ardougne teleport'
  | 'arena book'
  | 'armadyl bracers'
  | 'armadyl chainskirt'
  | 'armadyl chaps'
  | 'armadyl chestplate'
  | 'armadyl cloak'
  | 'armadyl coif'
  | 'armadyl crossbow'
  | 'armadyl crozier'
  | "armadyl d'hide"
  | "armadyl d'hide boots"
  | "armadyl d'hide shield"
  | 'armadyl dragonhide set'
  | 'armadyl full helm'
  | 'armadyl godsword'
  | 'armadyl godsword ornament kit'
  | 'armadyl helmet'
  | 'armadyl hilt'
  | 'armadyl kiteshield'
  | 'armadyl mitre'
  | 'armadyl page 1'
  | 'armadyl page 2'
  | 'armadyl page 3'
  | 'armadyl page 4'
  | 'armadyl platebody'
  | 'armadyl platelegs'
  | 'armadyl plateskirt'
  | 'armadyl robe legs'
  | 'armadyl robe top'
  | 'armadyl rune armour set (lg)'
  | 'armadyl rune armour set (sk)'
  | 'armadyl stole'
  | 'arrow shaft'
  | 'asgarnian ale'
  | 'asgarnian ale(4)'
  | 'asgarnian ale(m)'
  | 'asgarnian ale(m4)'
  | 'asgarnian hops'
  | 'asgarnian seed'
  | 'ashes'
  | 'assorted flowers'
  | 'astral rune'
  | 'asyn remains'
  | 'attack mix(1)'
  | 'attack mix(2)'
  | 'attack potion(1)'
  | 'attack potion(2)'
  | 'attack potion(3)'
  | 'attack potion(4)'
  | 'avantoe'
  | 'avantoe potion (unf)'
  | 'avantoe seed'
  | 'avernic defender hilt'
  | "axeman's folly"
  | "axeman's folly(4)"
  | "axeman's folly(m)"
  | "axeman's folly(m4)"
  | 'baby impling jar'
  | 'babydragon bones'
  | 'bag of salt'
  | 'bagged bluebells'
  | 'bagged daffodils'
  | 'bagged dead tree'
  | 'bagged flower'
  | 'bagged magic tree'
  | 'bagged maple tree'
  | 'bagged marigolds'
  | 'bagged nice tree'
  | 'bagged oak tree'
  | 'bagged plant 1'
  | 'bagged plant 2'
  | 'bagged plant 3'
  | 'bagged roses'
  | 'bagged sunflower'
  | 'bagged willow tree'
  | 'bagged yew tree'
  | 'baked potato'
  | 'ball of wool'
  | 'ballista limbs'
  | 'ballista spring'
  | 'banana'
  | 'banana sapling'
  | 'banana stew'
  | 'banana tree seed'
  | 'bananas(5)'
  | 'bandana eyepatch'
  | "bandit's brew"
  | 'bandos boots'
  | 'bandos bracers'
  | 'bandos chaps'
  | 'bandos chestplate'
  | 'bandos cloak'
  | 'bandos coif'
  | 'bandos crozier'
  | "bandos d'hide"
  | "bandos d'hide boots"
  | "bandos d'hide shield"
  | 'bandos dragonhide set'
  | 'bandos full helm'
  | 'bandos godsword'
  | 'bandos godsword ornament kit'
  | 'bandos hilt'
  | 'bandos kiteshield'
  | 'bandos mitre'
  | 'bandos page 1'
  | 'bandos page 2'
  | 'bandos page 3'
  | 'bandos page 4'
  | 'bandos platebody'
  | 'bandos platelegs'
  | 'bandos plateskirt'
  | 'bandos robe legs'
  | 'bandos robe top'
  | 'bandos rune armour set (lg)'
  | 'bandos rune armour set (sk)'
  | 'bandos stole'
  | 'bandos tassets'
  | 'barb bolttips'
  | 'barb-tail harpoon'
  | 'barbed bolts'
  | 'bark'
  | 'barley'
  | 'barley malt'
  | 'barley seed'
  | 'barrel'
  | 'barrows teleport'
  | 'basalt'
  | 'basilisk jaw'
  | 'basket'
  | 'bass'
  | 'bastion potion(1)'
  | 'bastion potion(2)'
  | 'bastion potion(3)'
  | 'bastion potion(4)'
  | 'bat bones'
  | 'batta tin'
  | 'battlefront teleport'
  | 'battlemage potion(1)'
  | 'battlemage potion(2)'
  | 'battlemage potion(3)'
  | 'battlemage potion(4)'
  | 'battlestaff'
  | 'beanie'
  | 'bear feet'
  | 'bear fur'
  | 'beer'
  | 'beer barrel'
  | 'beer glass'
  | 'beer tankard'
  | 'beginner wand'
  | 'belladonna seed'
  | 'berserker helm'
  | 'berserker necklace'
  | 'berserker necklace ornament kit'
  | 'berserker ring'
  | 'big bones'
  | 'big fishing net'
  | 'big pirate hat'
  | 'binding necklace'
  | 'bird house'
  | 'bird nest'
  | 'bird snare'
  | 'black 2h sword'
  | 'black axe'
  | 'black battleaxe'
  | 'black bead'
  | 'black beret'
  | 'black boater'
  | 'black boots'
  | 'black brutal'
  | 'black cane'
  | 'black cape'
  | 'black cavalier'
  | 'black chainbody'
  | 'black chinchompa'
  | 'black claws'
  | "black d'hide body"
  | "black d'hide body (g)"
  | "black d'hide body (t)"
  | "black d'hide chaps"
  | "black d'hide chaps (g)"
  | "black d'hide chaps (t)"
  | "black d'hide shield"
  | "black d'hide vamb"
  | 'black dagger'
  | 'black dagger(p)'
  | 'black dagger(p+)'
  | 'black dagger(p++)'
  | 'black dart'
  | 'black dart(p)'
  | 'black dart(p+)'
  | 'black dart(p++)'
  | 'black demon mask'
  | 'black desert robe'
  | 'black desert shirt'
  | 'black dragon leather'
  | 'black dragon mask'
  | 'black dragonhide'
  | 'black dragonhide set'
  | 'black elegant legs'
  | 'black elegant shirt'
  | 'black flowers'
  | 'black full helm'
  | 'black full helm (g)'
  | 'black full helm (t)'
  | 'black gold-trimmed set (lg)'
  | 'black gold-trimmed set (sk)'
  | 'black halberd'
  | 'black headband'
  | 'black helm (h1)'
  | 'black helm (h2)'
  | 'black helm (h3)'
  | 'black helm (h4)'
  | 'black helm (h5)'
  | 'black kiteshield'
  | 'black kiteshield (g)'
  | 'black kiteshield (t)'
  | 'black knife'
  | 'black knife(p)'
  | 'black knife(p+)'
  | 'black knife(p++)'
  | 'black leprechaun hat'
  | 'black longsword'
  | 'black mace'
  | 'black mask'
  | 'black mask (10)'
  | 'black med helm'
  | 'black nails'
  | 'black pickaxe'
  | 'black platebody'
  | 'black platebody (g)'
  | 'black platebody (h1)'
  | 'black platebody (h2)'
  | 'black platebody (h3)'
  | 'black platebody (h4)'
  | 'black platebody (h5)'
  | 'black platebody (t)'
  | 'black platelegs'
  | 'black platelegs (g)'
  | 'black platelegs (t)'
  | 'black plateskirt'
  | 'black plateskirt (g)'
  | 'black plateskirt (t)'
  | 'black robe'
  | 'black salamander'
  | 'black scimitar'
  | 'black set (lg)'
  | 'black set (sk)'
  | 'black shield (h1)'
  | 'black shield (h2)'
  | 'black shield (h3)'
  | 'black shield (h4)'
  | 'black shield (h5)'
  | 'black skirt'
  | 'black skirt (g)'
  | 'black skirt (t)'
  | 'black spear'
  | 'black spear(p)'
  | 'black spear(p+)'
  | 'black spear(p++)'
  | 'black spiky vambs'
  | 'black sq shield'
  | 'black sword'
  | 'black tourmaline core'
  | 'black toy horsey'
  | 'black trimmed set (lg)'
  | 'black trimmed set (sk)'
  | 'black unicorn mask'
  | 'black warhammer'
  | 'black warlock'
  | 'black wizard hat (g)'
  | 'black wizard hat (t)'
  | 'black wizard robe (g)'
  | 'black wizard robe (t)'
  | "blacksmith's helm"
  | 'blade of saeldor (inactive)'
  | 'blamish bark shell'
  | 'blamish blue shell'
  | 'blamish myre shell'
  | 'blamish ochre shell'
  | 'blamish red shell'
  | 'blessed spirit shield'
  | 'blood rune'
  | "blood'n'tar snelm"
  | 'bloody bracer'
  | 'blue beret'
  | 'blue boater'
  | 'blue boots'
  | 'blue cape'
  | "blue d'hide body"
  | "blue d'hide body (g)"
  | "blue d'hide body (t)"
  | "blue d'hide chaps"
  | "blue d'hide chaps (g)"
  | "blue d'hide chaps (t)"
  | "blue d'hide shield"
  | "blue d'hide vamb"
  | 'blue dark bow paint'
  | 'blue dragon leather'
  | 'blue dragon mask'
  | 'blue dragon scale'
  | 'blue dragonhide'
  | 'blue dragonhide set'
  | 'blue dye'
  | 'blue elegant blouse'
  | 'blue elegant legs'
  | 'blue elegant shirt'
  | 'blue elegant skirt'
  | 'blue feather'
  | 'blue firelighter'
  | 'blue flowers'
  | 'blue halloween mask'
  | 'blue hat'
  | 'blue headband'
  | 'blue partyhat'
  | 'blue robe bottoms'
  | 'blue robe top'
  | 'blue skirt'
  | 'blue skirt (g)'
  | 'blue skirt (t)'
  | 'blue spiky vambs'
  | 'blue wizard hat'
  | 'blue wizard hat (g)'
  | 'blue wizard hat (t)'
  | 'blue wizard robe'
  | 'blue wizard robe (g)'
  | 'blue wizard robe (t)'
  | 'bluegill'
  | 'blurberry special'
  | "bob's black shirt"
  | "bob's blue shirt"
  | "bob's green shirt"
  | "bob's purple shirt"
  | "bob's red shirt"
  | 'body rune'
  | 'body talisman'
  | 'body tiara'
  | 'bolt mould'
  | 'bolt of cloth'
  | 'bolt rack'
  | 'bone bolts'
  | 'bone club'
  | 'bone dagger'
  | 'bone dagger (p)'
  | 'bone dagger (p+)'
  | 'bone dagger (p++)'
  | 'bone spear'
  | 'bones'
  | 'bones to bananas'
  | 'bones to peaches'
  | 'book of balance page set'
  | 'book of darkness page set'
  | 'book of law page set'
  | 'book of war page set'
  | 'bookcase'
  | 'boots of brimstone'
  | 'boots of darkness'
  | 'boots of stone'
  | 'botanical pie'
  | 'bottle of wine'
  | 'bottled dragonbreath'
  | 'bottled dragonbreath (unpowered)'
  | 'bottomless compost bucket'
  | 'bounty target teleport'
  | 'bounty teleport scroll'
  | 'bow string'
  | 'bowl'
  | 'bowl of hot water'
  | 'bowl of water'
  | 'bowl wig'
  | 'box trap'
  | 'bracelet mould'
  | 'bracelet of clay'
  | 'bracelet of ethereum (uncharged)'
  | 'bracelet of slaughter'
  | 'brandy'
  | 'brass key'
  | 'brass necklace'
  | 'bread'
  | 'bread dough'
  | 'briefcase'
  | 'brimstone ring'
  | 'brine sabre'
  | 'broad arrowheads'
  | 'broad bolts'
  | 'broken bark snelm'
  | 'broken dragon hasta'
  | 'bronze 2h sword'
  | 'bronze arrow'
  | 'bronze arrow(p)'
  | 'bronze arrow(p+)'
  | 'bronze arrow(p++)'
  | 'bronze arrowtips'
  | 'bronze axe'
  | 'bronze bar'
  | 'bronze battleaxe'
  | 'bronze bolts'
  | 'bronze bolts (p)'
  | 'bronze bolts (p+)'
  | 'bronze bolts (p++)'
  | 'bronze bolts (unf)'
  | 'bronze boots'
  | 'bronze brutal'
  | 'bronze chainbody'
  | 'bronze claws'
  | 'bronze crossbow'
  | 'bronze crossbow (u)'
  | 'bronze dagger'
  | 'bronze dagger(p)'
  | 'bronze dagger(p+)'
  | 'bronze dagger(p++)'
  | 'bronze dart'
  | 'bronze dart tip'
  | 'bronze dart(p)'
  | 'bronze dart(p+)'
  | 'bronze dart(p++)'
  | 'bronze dragon mask'
  | 'bronze full helm'
  | 'bronze full helm (g)'
  | 'bronze full helm (t)'
  | 'bronze gold-trimmed set (lg)'
  | 'bronze gold-trimmed set (sk)'
  | 'bronze halberd'
  | 'bronze hasta'
  | 'bronze hasta(p)'
  | 'bronze hasta(p+)'
  | 'bronze hasta(p++)'
  | 'bronze javelin'
  | 'bronze javelin heads'
  | 'bronze javelin(p)'
  | 'bronze javelin(p+)'
  | 'bronze javelin(p++)'
  | 'bronze kiteshield'
  | 'bronze kiteshield (g)'
  | 'bronze kiteshield (t)'
  | 'bronze knife'
  | 'bronze knife(p)'
  | 'bronze knife(p+)'
  | 'bronze knife(p++)'
  | 'bronze limbs'
  | 'bronze longsword'
  | 'bronze mace'
  | 'bronze med helm'
  | 'bronze nails'
  | 'bronze pickaxe'
  | 'bronze platebody'
  | 'bronze platebody (g)'
  | 'bronze platebody (t)'
  | 'bronze platelegs'
  | 'bronze platelegs (g)'
  | 'bronze platelegs (t)'
  | 'bronze plateskirt'
  | 'bronze plateskirt (g)'
  | 'bronze plateskirt (t)'
  | 'bronze scimitar'
  | 'bronze set (lg)'
  | 'bronze set (sk)'
  | 'bronze spear'
  | 'bronze spear(p)'
  | 'bronze spear(p+)'
  | 'bronze spear(p++)'
  | 'bronze sq shield'
  | 'bronze sword'
  | 'bronze thrownaxe'
  | 'bronze trimmed set (lg)'
  | 'bronze trimmed set (sk)'
  | 'bronze warhammer'
  | 'bronze wire'
  | 'broodoo shield'
  | 'broodoo shield (10)'
  | 'brown apron'
  | 'brown headband'
  | 'brown toy horsey'
  | 'bruise blue snelm'
  | "bryophyta's essence"
  | "bryophyta's staff (uncharged)"
  | 'bucket'
  | 'bucket helm'
  | 'bucket helm (g)'
  | 'bucket of milk'
  | 'bucket of sand'
  | 'bucket of sap'
  | 'bucket of water'
  | 'bucket of wax'
  | 'bullseye lantern'
  | 'bullseye lantern (empty)'
  | 'bullseye lantern (unf)'
  | 'burning amulet(5)'
  | 'burnt bones'
  | 'burnt page'
  | 'butterfly jar'
  | 'butterfly net'
  | 'cabbage'
  | 'cabbage round shield'
  | 'cabbage seed'
  | 'cabbages(10)'
  | 'cactus seed'
  | 'cactus spine'
  | 'cadantine'
  | 'cadantine blood potion (unf)'
  | 'cadantine potion (unf)'
  | 'cadantine seed'
  | 'cadava berries'
  | 'cadavaberry seed'
  | 'cake'
  | 'cake tin'
  | 'calcite'
  | 'calquat fruit'
  | 'calquat keg'
  | 'calquat sapling'
  | 'calquat tree seed'
  | 'camelot teleport'
  | 'candle'
  | 'candle lantern'
  | 'cannon barrels'
  | 'cannon base'
  | 'cannon furnace'
  | 'cannon stand'
  | 'cannonball'
  | 'cape of skulls'
  | 'carrallangar teleport'
  | 'carved oak bench'
  | 'carved oak magic wardrobe'
  | 'carved oak table'
  | 'carved teak bench'
  | 'carved teak magic wardrobe'
  | 'carved teak table'
  | 'casket'
  | 'castle wars bracelet(3)'
  | 'cat mask'
  | 'cavalier mask'
  | 'cave eel'
  | 'cave goblin wire'
  | 'caviar'
  | 'celastrus bark'
  | 'celastrus sapling'
  | 'celastrus seed'
  | 'cemetery teleport'
  | 'chaos rune'
  | 'chaos talisman'
  | 'chaos tiara'
  | 'charcoal'
  | 'charge dragonstone jewellery scroll'
  | 'cheese'
  | 'cheese+tom batta'
  | "chef's delight"
  | "chef's delight(4)"
  | "chef's delight(m)"
  | "chef's delight(m4)"
  | "chef's hat"
  | 'chilli con carne'
  | 'chilli potato'
  | 'chinchompa'
  | 'chisel'
  | 'choc saturday'
  | 'choc-ice'
  | 'chocchip crunchies'
  | 'chocolate bar'
  | 'chocolate bomb'
  | 'chocolate cake'
  | 'chocolate dust'
  | 'chopped garlic'
  | 'chopped onion'
  | 'chopped tomato'
  | 'chopped tuna'
  | 'chopped ugthanki'
  | 'christmas cracker'
  | 'cider'
  | 'cider barrel'
  | 'cider(4)'
  | 'cider(m4)'
  | 'circular hide'
  | 'citizen shoes'
  | 'citizen top'
  | 'citizen trousers'
  | 'clay'
  | 'cleaning cloth'
  | 'cleaver'
  | 'climbing boots'
  | 'climbing boots (g)'
  | 'clockwork'
  | 'clue box'
  | 'coal'
  | 'cocktail glass'
  | 'cocktail guide'
  | 'cocktail shaker'
  | 'coconut'
  | 'coconut milk'
  | 'cod'
  | 'coif'
  | 'combat bracelet'
  | 'combat bracelet(4)'
  | 'combat bracelet(6)'
  | 'combat mix(1)'
  | 'combat mix(2)'
  | 'combat potion set'
  | 'combat potion(1)'
  | 'combat potion(2)'
  | 'combat potion(3)'
  | 'combat potion(4)'
  | 'common kebbit fur'
  | 'common tench'
  | 'comp ogre bow'
  | 'compost'
  | 'compost potion(1)'
  | 'compost potion(2)'
  | 'compost potion(3)'
  | 'compost potion(4)'
  | 'cooked chicken'
  | 'cooked chompy'
  | 'cooked crab meat'
  | 'cooked jubbly'
  | 'cooked karambwan'
  | 'cooked meat'
  | 'cooked oomlie wrap'
  | 'cooked rabbit'
  | 'cooked slimy eel'
  | 'cooked sweetcorn'
  | 'cooking apple'
  | 'copper ore'
  | 'cornflour'
  | 'cosmic rune'
  | 'cosmic talisman'
  | 'cosmic tiara'
  | 'cowhide'
  | "craw's bow (u)"
  | 'cream boots'
  | 'cream hat'
  | 'cream robe bottoms'
  | 'cream robe top'
  | 'crier bell'
  | 'crier coat'
  | 'crier hat'
  | 'crossbow'
  | 'crossbow string'
  | 'crude chair'
  | 'crunchy tray'
  | 'crushed nest'
  | 'crushed superior dragon bones'
  | 'crystal armour seed'
  | 'crystal ball'
  | 'crystal grail'
  | 'crystal key'
  | 'crystal of power'
  | 'crystal tool seed'
  | 'crystal weapon seed'
  | 'cup of hot water'
  | 'cup of tea'
  | 'cup of water'
  | 'cured yak-hide'
  | 'curry'
  | 'curry leaf'
  | 'curry sapling'
  | 'curry tree seed'
  | 'cyclops head'
  | 'dagannoth bones'
  | 'dagannoth hide'
  | "dagon'hai hat"
  | "dagon'hai robe bottom"
  | "dagon'hai robe top"
  | "dagon'hai robes set"
  | 'damaged monkey tail'
  | 'dareeyak teleport'
  | 'dark bow'
  | 'dark bow tie'
  | 'dark cavalier'
  | 'dark crab'
  | 'dark fishing bait'
  | 'dark infinity colour kit'
  | 'dark kebbit fur'
  | 'dark trousers'
  | 'dark tuxedo cuffs'
  | 'dark tuxedo jacket'
  | 'dark tuxedo shoes'
  | 'dashing kebbit fur'
  | 'death rune'
  | 'death talisman'
  | 'death tiara'
  | 'deerstalker'
  | 'defence mix(1)'
  | 'defence mix(2)'
  | 'defence potion(1)'
  | 'defence potion(2)'
  | 'defence potion(3)'
  | 'defence potion(4)'
  | 'demon feet'
  | 'desert boots'
  | 'desert camo legs'
  | 'desert camo top'
  | 'desert devil fur'
  | 'desert goat horn'
  | 'desert legs'
  | 'desert robe'
  | 'desert robes'
  | 'desert shirt'
  | 'desert top'
  | 'devout boots'
  | 'dexterous prayer scroll'
  | "dharok's armour set"
  | "dharok's greataxe"
  | "dharok's greataxe 0"
  | "dharok's helm"
  | "dharok's helm 0"
  | "dharok's platebody"
  | "dharok's platebody 0"
  | "dharok's platelegs"
  | "dharok's platelegs 0"
  | 'diamond'
  | 'diamond amulet'
  | 'diamond amulet (u)'
  | 'diamond bolt tips'
  | 'diamond bolts'
  | 'diamond bolts (e)'
  | 'diamond bracelet'
  | 'diamond dragon bolts'
  | 'diamond dragon bolts (e)'
  | 'diamond necklace'
  | 'diamond ring'
  | 'digsite teleport'
  | "dinh's bulwark"
  | 'disk of returning'
  | 'divine magic potion(1)'
  | 'divine magic potion(2)'
  | 'divine magic potion(3)'
  | 'divine magic potion(4)'
  | 'divine ranging potion(1)'
  | 'divine ranging potion(2)'
  | 'divine ranging potion(3)'
  | 'divine ranging potion(4)'
  | 'divine super attack potion(1)'
  | 'divine super attack potion(2)'
  | 'divine super attack potion(3)'
  | 'divine super attack potion(4)'
  | 'divine super combat potion(1)'
  | 'divine super combat potion(2)'
  | 'divine super combat potion(3)'
  | 'divine super combat potion(4)'
  | 'divine super defence potion(1)'
  | 'divine super defence potion(2)'
  | 'divine super defence potion(3)'
  | 'divine super defence potion(4)'
  | 'divine super strength potion(1)'
  | 'divine super strength potion(2)'
  | 'divine super strength potion(3)'
  | 'divine super strength potion(4)'
  | 'dodgy necklace'
  | 'doogle leaves'
  | 'dorgeshuun crossbow'
  | 'double eye patch'
  | 'draconic visage'
  | 'dragon 2h sword'
  | 'dragon armour set (lg)'
  | 'dragon armour set (sk)'
  | 'dragon arrow'
  | 'dragon arrow(p)'
  | 'dragon arrow(p+)'
  | 'dragon arrow(p++)'
  | 'dragon arrowtips'
  | 'dragon axe'
  | 'dragon battleaxe'
  | 'dragon bitter'
  | 'dragon bitter(4)'
  | 'dragon bitter(m)'
  | 'dragon bitter(m4)'
  | 'dragon bolts'
  | 'dragon bolts (p)'
  | 'dragon bolts (p+)'
  | 'dragon bolts (p++)'
  | 'dragon bolts (unf)'
  | 'dragon bones'
  | 'dragon boots'
  | 'dragon boots ornament kit'
  | 'dragon cane'
  | 'dragon chainbody'
  | 'dragon chainbody ornament kit'
  | 'dragon claws'
  | 'dragon crossbow'
  | 'dragon crossbow (u)'
  | 'dragon dagger'
  | 'dragon dagger(p)'
  | 'dragon dagger(p+)'
  | 'dragon dagger(p++)'
  | 'dragon dart'
  | 'dragon dart tip'
  | 'dragon dart(p)'
  | 'dragon dart(p+)'
  | 'dragon dart(p++)'
  | 'dragon defender ornament kit'
  | 'dragon full helm'
  | 'dragon full helm ornament kit'
  | 'dragon halberd'
  | 'dragon harpoon'
  | 'dragon hasta'
  | 'dragon hasta(p)'
  | 'dragon hasta(p+)'
  | 'dragon hasta(p++)'
  | 'dragon hunter crossbow'
  | 'dragon hunter lance'
  | 'dragon impling jar'
  | 'dragon javelin'
  | 'dragon javelin heads'
  | 'dragon javelin(p)'
  | 'dragon javelin(p+)'
  | 'dragon javelin(p++)'
  | 'dragon kiteshield'
  | 'dragon kiteshield ornament kit'
  | 'dragon knife'
  | 'dragon knife(p)'
  | 'dragon knife(p+)'
  | 'dragon knife(p++)'
  | 'dragon legs/skirt ornament kit'
  | 'dragon limbs'
  | 'dragon longsword'
  | 'dragon mace'
  | 'dragon med helm'
  | 'dragon metal lump'
  | 'dragon metal shard'
  | 'dragon metal slice'
  | 'dragon necklace'
  | 'dragon pickaxe'
  | 'dragon pickaxe upgrade kit'
  | 'dragon platebody'
  | 'dragon platebody ornament kit'
  | 'dragon platelegs'
  | 'dragon plateskirt'
  | 'dragon scale dust'
  | 'dragon scimitar'
  | 'dragon scimitar ornament kit'
  | 'dragon spear'
  | 'dragon spear(p)'
  | 'dragon spear(p+)'
  | 'dragon spear(p++)'
  | 'dragon sq shield'
  | 'dragon sq shield ornament kit'
  | 'dragon sword'
  | 'dragon thrownaxe'
  | 'dragon warhammer'
  | 'dragonbone necklace'
  | 'dragonfire shield'
  | 'dragonfire ward'
  | 'dragonfruit'
  | 'dragonfruit pie'
  | 'dragonfruit sapling'
  | 'dragonfruit tree seed'
  | 'dragonstone'
  | 'dragonstone amulet'
  | 'dragonstone amulet (u)'
  | 'dragonstone armour set'
  | 'dragonstone bolt tips'
  | 'dragonstone bolts'
  | 'dragonstone bolts (e)'
  | 'dragonstone boots'
  | 'dragonstone bracelet'
  | 'dragonstone dragon bolts'
  | 'dragonstone dragon bolts (e)'
  | 'dragonstone full helm'
  | 'dragonstone gauntlets'
  | 'dragonstone platebody'
  | 'dragonstone platelegs'
  | 'dragonstone ring'
  | 'drake bones'
  | "drake's claw"
  | "drake's tooth"
  | 'draynor manor teleport'
  | 'drift net'
  | "druid's robe"
  | "druid's robe top"
  | 'drunk dragon'
  | 'dual sai'
  | 'dust battlestaff'
  | 'dust rune'
  | 'dwarf cannon set'
  | 'dwarf weed'
  | 'dwarf weed potion (unf)'
  | 'dwarf weed seed'
  | 'dwarven helmet'
  | 'dwarven stout'
  | 'dwarven stout(4)'
  | 'dwarven stout(m)'
  | 'dwarven stout(m4)'
  | 'dwellberries'
  | 'dwellberry seed'
  | 'dynamite'
  | 'earmuffs'
  | 'earth battlestaff'
  | 'earth impling jar'
  | 'earth orb'
  | 'earth rune'
  | 'earth talisman'
  | 'earth tiara'
  | 'easter egg'
  | 'eclectic impling jar'
  | 'edible seaweed'
  | "efaritay's aid"
  | 'efh salt'
  | 'egg'
  | 'egg and tomato'
  | 'egg potato'
  | 'egg whisk'
  | 'elder chaos hood'
  | 'elder chaos robe'
  | 'elder chaos top'
  | 'elder maul'
  | 'eldritch orb'
  | 'elemental helmet'
  | 'elemental shield'
  | 'elemental sphere'
  | 'elemental talisman'
  | 'elven boots'
  | 'elven dawn'
  | 'elven gloves'
  | 'elven legwear'
  | 'elven signet'
  | 'elven skirt'
  | 'elven top'
  | 'elysian sigil'
  | 'elysian spirit shield'
  | 'emerald'
  | 'emerald amulet'
  | 'emerald amulet (u)'
  | 'emerald bolt tips'
  | 'emerald bolts'
  | 'emerald bolts (e)'
  | 'emerald bracelet'
  | 'emerald dragon bolts'
  | 'emerald dragon bolts (e)'
  | 'emerald necklace'
  | 'emerald ring'
  | 'empty candle lantern'
  | 'empty cup'
  | 'empty fishbowl'
  | 'empty oil lamp'
  | 'empty oil lantern'
  | 'empty plant pot'
  | 'empty sack'
  | 'enchant diamond'
  | 'enchant dragonstone'
  | 'enchant emerald or jade'
  | 'enchant onyx'
  | 'enchant ruby or topaz'
  | 'enchant sapphire or opal'
  | 'enchanted hat'
  | 'enchanted robe'
  | 'enchanted top'
  | 'energy mix(1)'
  | 'energy mix(2)'
  | 'energy potion(1)'
  | 'energy potion(2)'
  | 'energy potion(3)'
  | 'energy potion(4)'
  | 'enhanced crystal teleport seed'
  | 'ensouled abyssal head'
  | 'ensouled aviansie head'
  | 'ensouled bear head'
  | 'ensouled bloodveld head'
  | 'ensouled chaos druid head'
  | 'ensouled dagannoth head'
  | 'ensouled demon head'
  | 'ensouled dog head'
  | 'ensouled dragon head'
  | 'ensouled elf head'
  | 'ensouled giant head'
  | 'ensouled goblin head'
  | 'ensouled horror head'
  | 'ensouled imp head'
  | 'ensouled kalphite head'
  | 'ensouled minotaur head'
  | 'ensouled monkey head'
  | 'ensouled ogre head'
  | 'ensouled scorpion head'
  | 'ensouled troll head'
  | 'ensouled tzhaar head'
  | 'ensouled unicorn head'
  | 'equa leaves'
  | 'essence impling jar'
  | 'eternal boots'
  | 'eternal crystal'
  | 'eternal gem'
  | 'evil chicken feet'
  | 'evil chicken head'
  | 'evil chicken legs'
  | 'evil chicken wings'
  | 'expeditious bracelet'
  | 'explorer backpack'
  | 'extended antifire mix(1)'
  | 'extended antifire mix(2)'
  | 'extended antifire(1)'
  | 'extended antifire(2)'
  | 'extended antifire(3)'
  | 'extended antifire(4)'
  | 'extended super antifire mix(1)'
  | 'extended super antifire mix(2)'
  | 'extended super antifire(1)'
  | 'extended super antifire(2)'
  | 'extended super antifire(3)'
  | 'extended super antifire(4)'
  | 'eye of newt'
  | 'facemask'
  | 'fake beard'
  | 'falador teleport'
  | 'fancy hedge'
  | 'fancy teak dresser'
  | 'fancy tiara'
  | 'farseer helm'
  | 'fat snail'
  | 'fat snail meat'
  | 'fayrg bones'
  | 'feather'
  | 'fedora'
  | 'feldip hills teleport'
  | 'feldip weasel fur'
  | "fenkenstrain's castle teleport"
  | 'fez'
  | 'fibula piece'
  | 'filled plant pot'
  | 'fine cloth'
  | 'fire battlestaff'
  | 'fire orb'
  | 'fire rune'
  | 'fire talisman'
  | 'fire tiara'
  | 'fish chunks'
  | 'fish food'
  | 'fish offcuts'
  | 'fish pie'
  | 'fishing bait'
  | 'fishing mix(1)'
  | 'fishing mix(2)'
  | 'fishing potion(1)'
  | 'fishing potion(2)'
  | 'fishing potion(3)'
  | 'fishing potion(4)'
  | 'fishing rod'
  | 'fiyr remains'
  | 'flamtaer bracelet'
  | 'flamtaer hammer'
  | 'flared trousers'
  | 'flattened hide'
  | 'flax'
  | 'flighted ogre arrow'
  | 'fly fishing rod'
  | 'four-poster bed'
  | 'fremennik beige shirt'
  | 'fremennik black cloak'
  | 'fremennik blue cloak'
  | 'fremennik blue shirt'
  | 'fremennik boots'
  | 'fremennik brown cloak'
  | 'fremennik brown shirt'
  | 'fremennik cyan cloak'
  | 'fremennik gloves'
  | 'fremennik green cloak'
  | 'fremennik grey cloak'
  | 'fremennik grey shirt'
  | 'fremennik hat'
  | 'fremennik kilt'
  | 'fremennik pink cloak'
  | 'fremennik purple cloak'
  | 'fremennik red cloak'
  | 'fremennik red shirt'
  | 'fremennik robe'
  | 'fremennik skirt'
  | 'fremennik teal cloak'
  | 'fremennik yellow cloak'
  | 'fried mushrooms'
  | 'fried onions'
  | 'frog slippers'
  | 'frog-leather body'
  | 'frog-leather boots'
  | 'frog-leather chaps'
  | 'frozen whip mix'
  | 'fruit batta'
  | 'fruit blast'
  | 'frying pan'
  | 'fur'
  | 'fury ornament kit'
  | 'gadderhammer'
  | 'games necklace(8)'
  | 'garden pie'
  | 'gardening boots'
  | 'gardening trowel'
  | 'garlic'
  | 'garlic powder'
  | 'ghorrock teleport'
  | 'ghrazi rapier'
  | 'gianne dough'
  | "gianne's cook book"
  | 'giant boot'
  | 'giant egg sac(full)'
  | 'giant frog legs'
  | 'giant seaweed'
  | 'gilded 2h sword'
  | 'gilded armour set (lg)'
  | 'gilded armour set (sk)'
  | 'gilded axe'
  | 'gilded bench'
  | 'gilded boots'
  | 'gilded cape rack'
  | 'gilded chainbody'
  | 'gilded clock'
  | 'gilded coif'
  | "gilded d'hide body"
  | "gilded d'hide chaps"
  | "gilded d'hide vambs"
  | 'gilded dragonhide set'
  | 'gilded dresser'
  | 'gilded four-poster'
  | 'gilded full helm'
  | 'gilded hasta'
  | 'gilded kiteshield'
  | 'gilded magic wardrobe'
  | 'gilded med helm'
  | 'gilded pickaxe'
  | 'gilded platebody'
  | 'gilded platelegs'
  | 'gilded plateskirt'
  | 'gilded scimitar'
  | 'gilded spade'
  | 'gilded spear'
  | 'gilded sq shield'
  | 'gilded wardrobe'
  | 'gin'
  | 'glassblowing pipe'
  | 'gloves of darkness'
  | 'gloves of silence'
  | 'gnome goggles'
  | 'gnome scarf'
  | 'gnome spice'
  | 'gnomeball'
  | 'gnomebowl mould'
  | 'gnomish firelighter'
  | 'goat horn dust'
  | 'goblin book'
  | 'goblin mail'
  | 'goblin mask'
  | 'godsword blade'
  | 'godsword shard 1'
  | 'godsword shard 2'
  | 'godsword shard 3'
  | 'gold amulet'
  | 'gold amulet (u)'
  | 'gold bar'
  | 'gold bracelet'
  | 'gold elegant blouse'
  | 'gold elegant legs'
  | 'gold elegant shirt'
  | 'gold elegant skirt'
  | 'gold headband'
  | 'gold leaf'
  | 'gold necklace'
  | 'gold ore'
  | 'gold ring'
  | 'gold seal'
  | 'golden apron'
  | "golden chef's hat"
  | 'golden scarab'
  | 'golden statuette'
  | 'golovanova fruit top'
  | 'gourmet impling jar'
  | 'gout tuber'
  | 'graahk fur'
  | 'graahk headdress'
  | 'graahk legs'
  | 'graahk top'
  | 'grain'
  | 'grand seed pod'
  | 'granite (2kg)'
  | 'granite (500g)'
  | 'granite (5kg)'
  | 'granite body'
  | 'granite boots'
  | 'granite clamp'
  | 'granite gloves'
  | 'granite hammer'
  | 'granite helm'
  | 'granite legs'
  | 'granite longsword'
  | 'granite maul'
  | 'granite ring'
  | 'granite shield'
  | 'grape seed'
  | 'grapes'
  | 'greater demon mask'
  | 'greater siren'
  | 'green boater'
  | 'green boots'
  | 'green cape'
  | "green d'hide body"
  | "green d'hide body (g)"
  | "green d'hide body (t)"
  | "green d'hide chaps"
  | "green d'hide chaps (g)"
  | "green d'hide chaps (t)"
  | "green d'hide shield"
  | "green d'hide vamb"
  | 'green dark bow paint'
  | 'green dragon leather'
  | 'green dragon mask'
  | 'green dragonhide'
  | 'green dragonhide set'
  | 'green dye'
  | 'green elegant blouse'
  | 'green elegant legs'
  | 'green elegant shirt'
  | 'green elegant skirt'
  | 'green firelighter'
  | 'green halloween mask'
  | 'green hat'
  | 'green headband'
  | 'green partyhat'
  | 'green robe bottoms'
  | 'green robe top'
  | 'green spiky vambs'
  | "greenman's ale"
  | "greenman's ale(m)"
  | 'greenmans ale(4)'
  | 'greenmans ale(m4)'
  | 'grey boots'
  | 'grey gloves'
  | 'grey hat'
  | 'grey robe bottoms'
  | 'grey robe top'
  | 'grey toy horsey'
  | 'grey wolf fur'
  | 'grimy avantoe'
  | 'grimy cadantine'
  | 'grimy dwarf weed'
  | 'grimy guam leaf'
  | 'grimy harralander'
  | 'grimy irit leaf'
  | 'grimy kwuarm'
  | 'grimy lantadyme'
  | 'grimy marrentill'
  | 'grimy ranarr weed'
  | 'grimy snapdragon'
  | 'grimy tarromin'
  | 'grimy toadflax'
  | 'grimy torstol'
  | 'grog'
  | 'ground guam'
  | 'grubby key'
  | 'guam leaf'
  | 'guam potion (unf)'
  | 'guam seed'
  | 'guam tar'
  | 'guardian boots'
  | "guthan's armour set"
  | "guthan's chainskirt"
  | "guthan's chainskirt 0"
  | "guthan's helm"
  | "guthan's helm 0"
  | "guthan's platebody"
  | "guthan's platebody 0"
  | "guthan's warspear"
  | "guthan's warspear 0"
  | 'guthix armour set (lg)'
  | 'guthix armour set (sk)'
  | 'guthix balance(1)'
  | 'guthix balance(2)'
  | 'guthix balance(3)'
  | 'guthix balance(4)'
  | 'guthix bracers'
  | 'guthix chaps'
  | 'guthix cloak'
  | 'guthix coif'
  | 'guthix crozier'
  | "guthix d'hide"
  | "guthix d'hide boots"
  | "guthix d'hide shield"
  | 'guthix dragonhide set'
  | 'guthix full helm'
  | 'guthix kiteshield'
  | 'guthix mitre'
  | 'guthix mjolnir'
  | 'guthix page 1'
  | 'guthix page 2'
  | 'guthix page 3'
  | 'guthix page 4'
  | 'guthix platebody'
  | 'guthix platelegs'
  | 'guthix plateskirt'
  | 'guthix rest(1)'
  | 'guthix rest(2)'
  | 'guthix rest(3)'
  | 'guthix rest(4)'
  | 'guthix robe legs'
  | 'guthix robe top'
  | 'guthix stole'
  | 'hair'
  | 'half full wine jug'
  | 'half moon spectacles'
  | 'halloween mask set'
  | 'ham boots'
  | 'ham cloak'
  | 'ham gloves'
  | 'ham hood'
  | 'ham joint'
  | 'ham logo'
  | 'ham robe'
  | 'ham shirt'
  | 'hammer'
  | 'hammerstone hops'
  | 'hammerstone seed'
  | 'hard leather'
  | 'hard leather shield'
  | 'hardleather body'
  | 'harmonised orb'
  | 'harmony island teleport'
  | 'harpoon'
  | 'harralander'
  | 'harralander potion (unf)'
  | 'harralander seed'
  | 'harralander tar'
  | 'hat eyepatch'
  | 'headless arrow'
  | 'heavy ballista'
  | 'heavy frame'
  | 'helm of neitiznot'
  | 'herring'
  | 'highwayman mask'
  | 'hill giant club'
  | 'holy blessing'
  | 'holy book page set'
  | 'holy elixir'
  | 'holy mould'
  | 'holy sandals'
  | 'holy symbol'
  | 'holy wraps'
  | 'honourable blessing'
  | 'hood of darkness'
  | 'hosidius banner'
  | 'hosidius hood'
  | 'hosidius scarf'
  | 'hunter potion(1)'
  | 'hunter potion(2)'
  | 'hunter potion(3)'
  | 'hunter potion(4)'
  | "hunters' crossbow"
  | 'hunting mix(1)'
  | 'hunting mix(2)'
  | 'hydra bones'
  | 'hydra leather'
  | 'hydra tail'
  | "hydra's claw"
  | 'icy basalt'
  | 'imbued heart'
  | 'imp mask'
  | 'impling jar'
  | 'incomplete heavy ballista'
  | 'incomplete light ballista'
  | 'infinity boots'
  | 'infinity bottoms'
  | 'infinity gloves'
  | 'infinity hat'
  | 'infinity top'
  | 'initiate cuisse'
  | 'initiate harness m'
  | 'initiate hauberk'
  | 'initiate sallet'
  | 'inoculation bracelet'
  | "inquisitor's armour set"
  | "inquisitor's great helm"
  | "inquisitor's hauberk"
  | "inquisitor's mace"
  | "inquisitor's plateskirt"
  | 'insect repellent'
  | 'insulated boots'
  | 'iorwerth camp teleport'
  | 'irit leaf'
  | 'irit potion (unf)'
  | 'irit seed'
  | 'iron 2h sword'
  | 'iron arrow'
  | 'iron arrow(p)'
  | 'iron arrow(p+)'
  | 'iron arrow(p++)'
  | 'iron arrowtips'
  | 'iron axe'
  | 'iron bar'
  | 'iron battleaxe'
  | 'iron bolts'
  | 'iron bolts (p)'
  | 'iron bolts (p+)'
  | 'iron bolts (p++)'
  | 'iron bolts (unf)'
  | 'iron boots'
  | 'iron brutal'
  | 'iron chainbody'
  | 'iron claws'
  | 'iron crossbow'
  | 'iron crossbow (u)'
  | 'iron dagger'
  | 'iron dagger(p)'
  | 'iron dagger(p+)'
  | 'iron dagger(p++)'
  | 'iron dart'
  | 'iron dart tip'
  | 'iron dart(p)'
  | 'iron dart(p+)'
  | 'iron dart(p++)'
  | 'iron dragon mask'
  | 'iron full helm'
  | 'iron full helm (g)'
  | 'iron full helm (t)'
  | 'iron gold-trimmed set (lg)'
  | 'iron gold-trimmed set (sk)'
  | 'iron halberd'
  | 'iron hasta'
  | 'iron hasta(p)'
  | 'iron hasta(p+)'
  | 'iron hasta(p++)'
  | 'iron javelin'
  | 'iron javelin heads'
  | 'iron javelin(p)'
  | 'iron javelin(p+)'
  | 'iron javelin(p++)'
  | 'iron kiteshield'
  | 'iron kiteshield (g)'
  | 'iron kiteshield (t)'
  | 'iron knife'
  | 'iron knife(p)'
  | 'iron knife(p+)'
  | 'iron knife(p++)'
  | 'iron limbs'
  | 'iron longsword'
  | 'iron mace'
  | 'iron med helm'
  | 'iron nails'
  | 'iron ore'
  | 'iron pickaxe'
  | 'iron platebody'
  | 'iron platebody (g)'
  | 'iron platebody (t)'
  | 'iron platelegs'
  | 'iron platelegs (g)'
  | 'iron platelegs (t)'
  | 'iron plateskirt'
  | 'iron plateskirt (g)'
  | 'iron plateskirt (t)'
  | 'iron scimitar'
  | 'iron set (lg)'
  | 'iron set (sk)'
  | 'iron spear'
  | 'iron spear(p)'
  | 'iron spear(p+)'
  | 'iron spear(p++)'
  | 'iron spit'
  | 'iron sq shield'
  | 'iron sword'
  | 'iron thrownaxe'
  | 'iron trimmed set (lg)'
  | 'iron trimmed set (sk)'
  | 'iron warhammer'
  | 'ivory comb'
  | 'jade'
  | 'jade amulet'
  | 'jade amulet (u)'
  | 'jade bolt tips'
  | 'jade bracelet'
  | 'jade dragon bolts'
  | 'jade dragon bolts (e)'
  | 'jade machete'
  | 'jade necklace'
  | 'jade ring'
  | 'jangerberries'
  | 'jangerberry seed'
  | 'jar of chemicals'
  | 'jar of darkness'
  | 'jar of decay'
  | 'jar of dirt'
  | 'jar of dreams'
  | 'jar of eyes'
  | 'jar of miasma'
  | 'jar of sand'
  | 'jar of souls'
  | 'jar of stone'
  | 'jar of swamp'
  | 'javelin shaft'
  | 'jester cape'
  | 'jogre bones'
  | 'jug'
  | 'jug of water'
  | 'jug of wine'
  | 'jungle camo legs'
  | 'jungle camo top'
  | 'jungle demon mask'
  | 'justiciar armour set'
  | 'justiciar chestguard'
  | 'justiciar faceguard'
  | 'justiciar legguards'
  | 'jute fibre'
  | 'jute seed'
  | 'karambwan vessel'
  | 'karidian disguise'
  | "karil's armour set"
  | "karil's coif"
  | "karil's coif 0"
  | "karil's crossbow"
  | "karil's crossbow 0"
  | "karil's leatherskirt"
  | "karil's leatherskirt 0"
  | "karil's leathertop"
  | "karil's leathertop 0"
  | 'katana'
  | 'kebab'
  | 'kebab mix'
  | 'kebbit bolts'
  | 'kebbit claws'
  | 'kebbit spike'
  | 'kebbit teeth'
  | 'kebbit teeth dust'
  | 'keg of beer'
  | 'kharidian headpiece'
  | 'kharyrll teleport'
  | 'king worm'
  | 'kitchen knife'
  | 'kitchen table'
  | 'knife'
  | 'kodai insignia'
  | 'kodai wand'
  | 'kraken tentacle'
  | 'krandorian hops'
  | 'krandorian seed'
  | 'kwuarm'
  | 'kwuarm potion (unf)'
  | 'kwuarm seed'
  | 'kyatt fur'
  | 'kyatt hat'
  | 'kyatt legs'
  | 'kyatt top'
  | 'lantadyme'
  | 'lantadyme potion (unf)'
  | 'lantadyme seed'
  | 'lantern lens'
  | 'large oak bed'
  | 'large teak bed'
  | 'larupia fur'
  | 'larupia hat'
  | 'larupia legs'
  | 'larupia top'
  | 'lassar teleport'
  | 'lava battlestaff'
  | 'lava dragon bones'
  | 'lava dragon mask'
  | 'lava rune'
  | 'lava scale'
  | 'lava scale shard'
  | 'lava staff upgrade kit'
  | 'law rune'
  | 'leaf-bladed battleaxe'
  | 'leaf-bladed sword'
  | 'lean snail'
  | 'lean snail meat'
  | 'leaping salmon'
  | 'leaping sturgeon'
  | 'leaping trout'
  | 'leather'
  | 'leather body'
  | 'leather body (g)'
  | 'leather boots'
  | 'leather chaps'
  | 'leather chaps (g)'
  | 'leather cowl'
  | 'leather gloves'
  | 'leather vambraces'
  | 'left eye patch'
  | 'lemon'
  | 'lemon chunks'
  | 'lemon slices'
  | 'leprechaun hat'
  | 'lesser demon mask'
  | 'light ballista'
  | 'light bow tie'
  | 'light frame'
  | 'light infinity colour kit'
  | 'light orb'
  | 'light trousers'
  | 'light tuxedo cuffs'
  | 'light tuxedo jacket'
  | 'light tuxedo shoes'
  | 'lime'
  | 'lime chunks'
  | 'lime slices'
  | 'limestone'
  | 'limestone brick'
  | 'limpwurt root'
  | 'limpwurt seed'
  | 'linen'
  | 'lizardman fang'
  | 'loar remains'
  | 'lobster'
  | 'lobster pot'
  | 'lockpick'
  | 'locust meat'
  | 'logs'
  | 'long kebbit bolts'
  | 'long kebbit spike'
  | 'longbow'
  | 'longbow (u)'
  | 'loop half of key'
  | 'lovakengj banner'
  | 'lovakengj hood'
  | 'lovakengj scarf'
  | 'lumberyard teleport'
  | 'lumbridge graveyard teleport'
  | 'lumbridge teleport'
  | 'lunar isle teleport'
  | 'm. treasure chest'
  | 'machete'
  | 'mackerel'
  | "mage's book"
  | 'magic bird house'
  | 'magic box'
  | 'magic cape rack'
  | 'magic comp bow'
  | 'magic essence mix(1)'
  | 'magic essence mix(2)'
  | 'magic fang'
  | 'magic logs'
  | 'magic longbow'
  | 'magic longbow (u)'
  | 'magic mix(1)'
  | 'magic mix(2)'
  | 'magic potion(1)'
  | 'magic potion(2)'
  | 'magic potion(3)'
  | 'magic potion(4)'
  | 'magic pyre logs'
  | 'magic roots'
  | 'magic sapling'
  | 'magic seed'
  | 'magic shield'
  | 'magic shortbow'
  | 'magic shortbow (u)'
  | 'magic shortbow scroll'
  | 'magic staff'
  | 'magic stock'
  | 'magic stone'
  | 'magic string'
  | 'magpie impling jar'
  | 'mahogany armchair'
  | 'mahogany armour case'
  | 'mahogany bench'
  | 'mahogany bird house'
  | 'mahogany bookcase'
  | 'mahogany cape rack'
  | 'mahogany dresser'
  | 'mahogany fancy dress box'
  | 'mahogany logs'
  | 'mahogany magic wardrobe'
  | 'mahogany plank'
  | 'mahogany pyre log'
  | 'mahogany sapling'
  | 'mahogany seed'
  | 'mahogany stock'
  | 'mahogany table'
  | 'mahogany toy box'
  | 'mahogany wardrobe'
  | 'malediction shard 1'
  | 'malediction shard 2'
  | 'malediction shard 3'
  | 'malediction ward'
  | 'manta ray'
  | 'maple bird house'
  | 'maple blackjack'
  | 'maple blackjack(d)'
  | 'maple blackjack(o)'
  | 'maple logs'
  | 'maple longbow'
  | 'maple longbow (u)'
  | 'maple pyre logs'
  | 'maple roots'
  | 'maple sapling'
  | 'maple seed'
  | 'maple shield'
  | 'maple shortbow'
  | 'maple shortbow (u)'
  | 'maple stock'
  | 'marble block'
  | 'marble cape rack'
  | 'marble magic wardrobe'
  | 'marigold seed'
  | 'marigolds'
  | 'marrentill'
  | 'marrentill potion (unf)'
  | 'marrentill seed'
  | 'marrentill tar'
  | 'mask of ranul'
  | 'master scroll book (empty)'
  | 'master wand'
  | 'mature cider'
  | 'mature wmb'
  | 'meat pie'
  | 'meat pizza'
  | 'meat tenderiser'
  | 'menaphite purple hat'
  | 'menaphite purple kilt'
  | 'menaphite purple robe'
  | 'menaphite purple top'
  | 'menaphite red hat'
  | 'menaphite red kilt'
  | 'menaphite red robe'
  | 'menaphite red top'
  | 'merfolk trident'
  | 'minced meat'
  | 'mind altar teleport'
  | 'mind bomb(4)'
  | 'mind bomb(m4)'
  | 'mind helmet'
  | 'mind rune'
  | 'mind shield'
  | 'mind talisman'
  | 'mind tiara'
  | 'mining helmet'
  | 'mint cake'
  | 'mirror shield'
  | 'mist battlestaff'
  | 'mist rune'
  | 'mith crossbow'
  | 'mith grapple'
  | 'mith grapple tip'
  | 'mithril 2h sword'
  | 'mithril arrow'
  | 'mithril arrow(p)'
  | 'mithril arrow(p+)'
  | 'mithril arrow(p++)'
  | 'mithril arrowtips'
  | 'mithril axe'
  | 'mithril bar'
  | 'mithril battleaxe'
  | 'mithril bolts'
  | 'mithril bolts (p)'
  | 'mithril bolts (p+)'
  | 'mithril bolts (p++)'
  | 'mithril bolts (unf)'
  | 'mithril boots'
  | 'mithril brutal'
  | 'mithril chainbody'
  | 'mithril claws'
  | 'mithril crossbow (u)'
  | 'mithril dagger'
  | 'mithril dagger(p)'
  | 'mithril dagger(p+)'
  | 'mithril dagger(p++)'
  | 'mithril dart'
  | 'mithril dart tip'
  | 'mithril dart(p)'
  | 'mithril dart(p+)'
  | 'mithril dart(p++)'
  | 'mithril dragon mask'
  | 'mithril full helm'
  | 'mithril full helm (g)'
  | 'mithril full helm (t)'
  | 'mithril gold-trimmed set (lg)'
  | 'mithril gold-trimmed set (sk)'
  | 'mithril halberd'
  | 'mithril hasta'
  | 'mithril hasta(p)'
  | 'mithril hasta(p+)'
  | 'mithril hasta(p++)'
  | 'mithril javelin'
  | 'mithril javelin heads'
  | 'mithril javelin(p)'
  | 'mithril javelin(p+)'
  | 'mithril javelin(p++)'
  | 'mithril kiteshield'
  | 'mithril kiteshield (g)'
  | 'mithril kiteshield (t)'
  | 'mithril knife'
  | 'mithril knife(p)'
  | 'mithril knife(p+)'
  | 'mithril knife(p++)'
  | 'mithril limbs'
  | 'mithril longsword'
  | 'mithril mace'
  | 'mithril med helm'
  | 'mithril nails'
  | 'mithril ore'
  | 'mithril pickaxe'
  | 'mithril platebody'
  | 'mithril platebody (g)'
  | 'mithril platebody (t)'
  | 'mithril platelegs'
  | 'mithril platelegs (g)'
  | 'mithril platelegs (t)'
  | 'mithril plateskirt'
  | 'mithril plateskirt (g)'
  | 'mithril plateskirt (t)'
  | 'mithril scimitar'
  | 'mithril seeds'
  | 'mithril set (lg)'
  | 'mithril set (sk)'
  | 'mithril spear'
  | 'mithril spear(p)'
  | 'mithril spear(p+)'
  | 'mithril spear(p++)'
  | 'mithril sq shield'
  | 'mithril sword'
  | 'mithril thrownaxe'
  | 'mithril trimmed set (lg)'
  | 'mithril trimmed set (sk)'
  | 'mithril warhammer'
  | 'mixed flowers'
  | 'mole claw'
  | 'mole skin'
  | 'mole slippers'
  | 'molten glass'
  | "monk's robe"
  | "monk's robe (g)"
  | "monk's robe (t)"
  | "monk's robe top"
  | "monk's robe top (g)"
  | "monk's robe top (t)"
  | 'monkey bar'
  | 'monkey bones'
  | 'monkey nuts'
  | 'monkey tail'
  | 'monkfish'
  | 'monocle'
  | 'moonlight mead'
  | 'moonlight mead(4)'
  | 'moonlight mead(m)'
  | 'moonlight mead(m4)'
  | "morrigan's javelin"
  | "morrigan's throwing axe"
  | 'mort myre fungus'
  | 'mort myre pear'
  | 'mort myre stem'
  | "mort'ton teleport"
  | "mos le'harmless teleport"
  | 'mottled eel'
  | 'mud battlestaff'
  | 'mud pie'
  | 'mud rune'
  | 'muddy key'
  | "mummy's body"
  | "mummy's feet"
  | "mummy's hands"
  | "mummy's head"
  | "mummy's legs"
  | 'mushroom'
  | 'mushroom & onion'
  | 'mushroom pie'
  | 'mushroom potato'
  | 'mushroom spore'
  | 'musketeer hat'
  | 'musketeer pants'
  | 'musketeer tabard'
  | 'myre snelm'
  | 'mystic air staff'
  | 'mystic boots'
  | 'mystic boots (dark)'
  | 'mystic boots (dusk)'
  | 'mystic boots (light)'
  | 'mystic dust staff'
  | 'mystic earth staff'
  | 'mystic fire staff'
  | 'mystic gloves'
  | 'mystic gloves (dark)'
  | 'mystic gloves (dusk)'
  | 'mystic gloves (light)'
  | 'mystic hat'
  | 'mystic hat (dark)'
  | 'mystic hat (dusk)'
  | 'mystic hat (light)'
  | 'mystic lava staff'
  | 'mystic mist staff'
  | 'mystic mud staff'
  | 'mystic robe bottom'
  | 'mystic robe bottom (dark)'
  | 'mystic robe bottom (dusk)'
  | 'mystic robe bottom (light)'
  | 'mystic robe top'
  | 'mystic robe top (dark)'
  | 'mystic robe top (dusk)'
  | 'mystic robe top (light)'
  | 'mystic set (blue)'
  | 'mystic set (dark)'
  | 'mystic set (dusk)'
  | 'mystic set (light)'
  | 'mystic smoke staff'
  | 'mystic steam staff'
  | 'mystic water staff'
  | 'nail beast nails'
  | 'nardah teleport'
  | 'nasturtium seed'
  | 'nasturtiums'
  | 'nature impling jar'
  | 'nature rune'
  | 'nature talisman'
  | 'nature tiara'
  | 'navy cavalier'
  | 'necklace mould'
  | 'necklace of anguish'
  | 'necklace of faith'
  | 'necklace of passage(5)'
  | 'needle'
  | 'neitiznot shield'
  | 'nice hedge'
  | 'nightmare staff'
  | 'ninja impling jar'
  | 'noose wand'
  | 'nose peg'
  | 'numulite'
  | 'nunchaku'
  | 'oak armchair'
  | 'oak armour case'
  | 'oak bed'
  | 'oak bench'
  | 'oak bird house'
  | 'oak blackjack(d)'
  | 'oak blackjack(o)'
  | 'oak bookcase'
  | 'oak cape rack'
  | 'oak chair'
  | 'oak clock'
  | 'oak dining table'
  | 'oak drawers'
  | 'oak dresser'
  | 'oak fancy dress box'
  | 'oak kitchen table'
  | 'oak logs'
  | 'oak longbow'
  | 'oak longbow (u)'
  | 'oak magic wardrobe'
  | 'oak plank'
  | 'oak pyre logs'
  | 'oak roots'
  | 'oak sapling'
  | 'oak shaving stand'
  | 'oak shield'
  | 'oak shortbow'
  | 'oak shortbow (u)'
  | 'oak stock'
  | 'oak toy box'
  | 'oak treasure chest'
  | 'oak wardrobe'
  | 'obsidian armour set'
  | 'obsidian cape'
  | 'obsidian cape (r)'
  | 'obsidian helmet'
  | 'obsidian platebody'
  | 'obsidian platelegs'
  | 'occult necklace'
  | 'occult ornament kit'
  | 'ochre snelm'
  | 'odium shard 1'
  | 'odium shard 2'
  | 'odium shard 3'
  | 'odium ward'
  | 'ogre arrow'
  | 'ogre arrow shaft'
  | 'ogre coffin key'
  | 'oil lamp'
  | 'oil lantern'
  | 'oil lantern frame'
  | 'old demon mask'
  | 'old school bond'
  | 'olive oil(1)'
  | 'olive oil(2)'
  | 'olive oil(3)'
  | 'olive oil(4)'
  | 'onion'
  | 'onion & tomato'
  | 'onion seed'
  | 'onions(10)'
  | 'onyx'
  | 'onyx amulet'
  | 'onyx amulet (u)'
  | 'onyx bolt tips'
  | 'onyx bolts'
  | 'onyx bolts (e)'
  | 'onyx bracelet'
  | 'onyx dragon bolts'
  | 'onyx dragon bolts (e)'
  | 'onyx necklace'
  | 'onyx ring'
  | 'opal'
  | 'opal amulet'
  | 'opal amulet (u)'
  | 'opal bolt tips'
  | 'opal bolts'
  | 'opal bolts (e)'
  | 'opal bracelet'
  | 'opal dragon bolts'
  | 'opal dragon bolts (e)'
  | 'opal machete'
  | 'opal necklace'
  | 'opal ring'
  | 'opulent table'
  | 'orange'
  | 'orange boater'
  | 'orange cape'
  | 'orange chunks'
  | 'orange dye'
  | 'orange feather'
  | 'orange flowers'
  | 'orange salamander'
  | 'orange sapling'
  | 'orange slices'
  | 'orange tree seed'
  | 'oranges(5)'
  | 'ornate maul handle'
  | 'ourg bones'
  | 'oyster'
  | 'oyster pearl'
  | 'oyster pearls'
  | 'paddewwa teleport'
  | 'palm sapling'
  | 'palm tree seed'
  | 'pantaloons'
  | 'papaya fruit'
  | 'papaya sapling'
  | 'papaya tree seed'
  | 'papyrus'
  | 'partyhat & specs'
  | 'partyhat set'
  | 'pastry dough'
  | 'pat of butter'
  | 'peaceful blessing'
  | 'pearl bolt tips'
  | 'pearl bolts'
  | 'pearl bolts (e)'
  | 'pearl dragon bolts'
  | 'pearl dragon bolts (e)'
  | 'pegasian boots'
  | 'pegasian crystal'
  | 'penguin mask'
  | 'pest control teleport'
  | 'pestle and mortar'
  | "pharaoh's sceptre"
  | "pharaoh's sceptre (3)"
  | 'phoenix necklace'
  | 'phrin remains'
  | 'pie dish'
  | 'pie recipe book'
  | 'pie shell'
  | 'pike'
  | 'pile of salt'
  | 'pineapple'
  | 'pineapple chunks'
  | 'pineapple pizza'
  | 'pineapple punch'
  | 'pineapple ring'
  | 'pineapple sapling'
  | 'pineapple seed'
  | 'pink boater'
  | 'pink boots'
  | 'pink cape'
  | 'pink elegant blouse'
  | 'pink elegant legs'
  | 'pink elegant shirt'
  | 'pink elegant skirt'
  | 'pink hat'
  | 'pink headband'
  | 'pink robe bottoms'
  | 'pink robe top'
  | 'pink skirt'
  | 'pirate bandana'
  | 'pirate boots'
  | 'pirate hat & patch'
  | 'pirate leggings'
  | "pirate's hat"
  | "pirate's hook"
  | 'piscarilius banner'
  | 'piscarilius hood'
  | 'piscarilius scarf'
  | 'piscatoris teleport'
  | 'pith helmet'
  | 'pitta bread'
  | 'pizza base'
  | 'plain pizza'
  | 'plank'
  | 'plant cure'
  | 'poison'
  | 'poison chalice'
  | 'poison ivy berries'
  | 'poison ivy seed'
  | 'polar camo legs'
  | 'polar camo top'
  | 'polar kebbit fur'
  | 'polished buttons'
  | 'pot'
  | 'pot lid'
  | 'pot of cornflour'
  | 'pot of cream'
  | 'pot of flour'
  | 'potato'
  | 'potato cactus'
  | 'potato cactus seed'
  | 'potato seed'
  | 'potato with butter'
  | 'potato with cheese'
  | 'potatoes(10)'
  | 'pottery scarab'
  | 'pottery statuette'
  | 'prayer mix(1)'
  | 'prayer mix(2)'
  | 'prayer potion(1)'
  | 'prayer potion(2)'
  | 'prayer potion(3)'
  | 'prayer potion(4)'
  | "premade blurb' sp."
  | 'premade c+t batta'
  | "premade ch' crunch"
  | 'premade choc bomb'
  | "premade choc s'dy"
  | "premade dr' dragon"
  | "premade fr' blast"
  | "premade fr't batta"
  | "premade p' punch"
  | "premade s'y crunch"
  | 'premade sgg'
  | "premade t'd batta"
  | "premade t'd crunch"
  | 'premade ttl'
  | 'premade veg ball'
  | 'premade veg batta'
  | "premade w'm batta"
  | "premade w'm crun'"
  | "premade wiz blz'd"
  | 'premade worm hole'
  | 'priest gown'
  | 'primordial boots'
  | 'primordial crystal'
  | 'proboscis'
  | 'proselyte cuisse'
  | 'proselyte harness f'
  | 'proselyte harness m'
  | 'proselyte hauberk'
  | 'proselyte sallet'
  | 'proselyte tasset'
  | 'pumpkin'
  | 'pure essence'
  | 'purple boater'
  | 'purple boots'
  | 'purple cape'
  | 'purple dye'
  | 'purple elegant blouse'
  | 'purple elegant legs'
  | 'purple elegant shirt'
  | 'purple elegant skirt'
  | 'purple firelighter'
  | 'purple flowers'
  | 'purple gloves'
  | 'purple hat'
  | 'purple partyhat'
  | 'purple robe bottoms'
  | 'purple robe top'
  | 'purple sweets'
  | 'pyre logs'
  | 'pyrophosphite'
  | 'rabbit foot'
  | 'rabbit snare'
  | 'rain bow'
  | 'rainbow fish'
  | 'rake'
  | 'ranarr potion (unf)'
  | 'ranarr seed'
  | 'ranarr weed'
  | 'ranger boots'
  | 'ranger gloves'
  | "rangers' tights"
  | "rangers' tunic"
  | 'ranging mix(1)'
  | 'ranging mix(2)'
  | 'ranging potion(1)'
  | 'ranging potion(2)'
  | 'ranging potion(3)'
  | 'ranging potion(4)'
  | 'raurg bones'
  | 'raw admiral pie'
  | 'raw anchovies'
  | 'raw anglerfish'
  | 'raw bass'
  | 'raw bear meat'
  | 'raw beast meat'
  | 'raw beef'
  | 'raw bird meat'
  | 'raw cave eel'
  | 'raw chicken'
  | 'raw chompy'
  | 'raw cod'
  | 'raw dark crab'
  | 'raw fish pie'
  | 'raw garden pie'
  | 'raw herring'
  | 'raw jubbly'
  | 'raw karambwan'
  | 'raw lobster'
  | 'raw mackerel'
  | 'raw manta ray'
  | 'raw monkfish'
  | 'raw mud pie'
  | 'raw oomlie'
  | 'raw pike'
  | 'raw rabbit'
  | 'raw rainbow fish'
  | 'raw rat meat'
  | 'raw salmon'
  | 'raw sardine'
  | 'raw sea turtle'
  | 'raw shark'
  | 'raw shrimps'
  | 'raw slimy eel'
  | 'raw summer pie'
  | 'raw swordfish'
  | 'raw trout'
  | 'raw tuna'
  | 'raw ugthanki meat'
  | 'raw wild pie'
  | 'raw yak meat'
  | 'red bead'
  | 'red beret'
  | 'red boater'
  | 'red boots'
  | 'red cape'
  | 'red cavalier'
  | 'red chinchompa'
  | "red d'hide body"
  | "red d'hide body (g)"
  | "red d'hide body (t)"
  | "red d'hide chaps"
  | "red d'hide chaps (g)"
  | "red d'hide chaps (t)"
  | "red d'hide shield"
  | "red d'hide vamb"
  | 'red dragon leather'
  | 'red dragon mask'
  | 'red dragonhide'
  | 'red dragonhide set'
  | 'red dye'
  | 'red elegant blouse'
  | 'red elegant legs'
  | 'red elegant shirt'
  | 'red elegant skirt'
  | 'red feather'
  | 'red firelighter'
  | 'red flowers'
  | 'red gloves'
  | 'red halloween mask'
  | 'red hat'
  | 'red headband'
  | 'red partyhat'
  | 'red robe bottoms'
  | 'red robe top'
  | 'red salamander'
  | "red spiders' eggs"
  | 'red spiky vambs'
  | 'red topaz'
  | 'red topaz machete'
  | 'redberries'
  | 'redberry pie'
  | 'redberry seed'
  | 'redwood bird house'
  | 'redwood logs'
  | 'redwood pyre logs'
  | 'redwood sapling'
  | 'redwood shield'
  | 'redwood tree seed'
  | 'regen bracelet'
  | "relicym's balm(1)"
  | "relicym's balm(2)"
  | "relicym's balm(3)"
  | "relicym's balm(4)"
  | "relicym's mix(1)"
  | "relicym's mix(2)"
  | 'restore mix(1)'
  | 'restore mix(2)'
  | 'restore potion(1)'
  | 'restore potion(2)'
  | 'restore potion(3)'
  | 'restore potion(4)'
  | 'revenant cave teleport'
  | 'revenant ether'
  | 'ribcage piece'
  | 'right eye patch'
  | 'ring mould'
  | 'ring of 3rd age'
  | 'ring of coins'
  | 'ring of dueling(8)'
  | 'ring of forging'
  | 'ring of life'
  | 'ring of nature'
  | 'ring of pursuit'
  | 'ring of recoil'
  | 'ring of returning(5)'
  | 'ring of stone'
  | 'ring of suffering'
  | 'ring of the gods'
  | 'ring of wealth'
  | 'ring of wealth (5)'
  | 'ring of wealth scroll'
  | 'riyl remains'
  | 'roast beast meat'
  | 'roast bird meat'
  | 'roast rabbit'
  | 'robe bottom of darkness'
  | 'robe top of darkness'
  | 'robin hood hat'
  | 'rock hammer'
  | 'rock thrownhammer'
  | 'rock-climbing boots'
  | 'rock-shell boots'
  | 'rock-shell chunk'
  | 'rock-shell gloves'
  | 'rock-shell helm'
  | 'rock-shell legs'
  | 'rock-shell plate'
  | 'rock-shell shard'
  | 'rock-shell splinter'
  | 'rocking chair'
  | 'roe'
  | 'rolling pin'
  | 'rope'
  | 'rosemary'
  | 'rosemary seed'
  | 'royal crown'
  | 'royal gown bottom'
  | 'royal gown top'
  | 'royal sceptre'
  | 'ruby'
  | 'ruby amulet'
  | 'ruby amulet (u)'
  | 'ruby bolt tips'
  | 'ruby bolts'
  | 'ruby bolts (e)'
  | 'ruby bracelet'
  | 'ruby dragon bolts'
  | 'ruby dragon bolts (e)'
  | 'ruby harvest'
  | 'ruby necklace'
  | 'ruby ring'
  | 'rune 2h sword'
  | 'rune armour set (lg)'
  | 'rune armour set (sk)'
  | 'rune arrow'
  | 'rune arrow(p)'
  | 'rune arrow(p+)'
  | 'rune arrow(p++)'
  | 'rune arrowtips'
  | 'rune axe'
  | 'rune battleaxe'
  | 'rune boots'
  | 'rune brutal'
  | 'rune cane'
  | 'rune chainbody'
  | 'rune claws'
  | 'rune crossbow'
  | 'rune dagger'
  | 'rune dagger(p)'
  | 'rune dagger(p+)'
  | 'rune dagger(p++)'
  | 'rune dart'
  | 'rune dart tip'
  | 'rune dart(p)'
  | 'rune dart(p+)'
  | 'rune dart(p++)'
  | 'rune defender ornament kit'
  | 'rune dragon mask'
  | 'rune essence'
  | 'rune full helm'
  | 'rune full helm (g)'
  | 'rune full helm (t)'
  | 'rune gold-trimmed set (lg)'
  | 'rune gold-trimmed set (sk)'
  | 'rune halberd'
  | 'rune hasta'
  | 'rune hasta(p)'
  | 'rune hasta(p+)'
  | 'rune hasta(p++)'
  | 'rune helm (h1)'
  | 'rune helm (h2)'
  | 'rune helm (h3)'
  | 'rune helm (h4)'
  | 'rune helm (h5)'
  | 'rune javelin'
  | 'rune javelin heads'
  | 'rune javelin(p)'
  | 'rune javelin(p+)'
  | 'rune javelin(p++)'
  | 'rune kiteshield'
  | 'rune kiteshield (g)'
  | 'rune kiteshield (t)'
  | 'rune knife'
  | 'rune knife(p)'
  | 'rune knife(p+)'
  | 'rune knife(p++)'
  | 'rune longsword'
  | 'rune mace'
  | 'rune med helm'
  | 'rune nails'
  | 'rune pickaxe'
  | 'rune platebody'
  | 'rune platebody (g)'
  | 'rune platebody (h1)'
  | 'rune platebody (h2)'
  | 'rune platebody (h3)'
  | 'rune platebody (h4)'
  | 'rune platebody (h5)'
  | 'rune platebody (t)'
  | 'rune platelegs'
  | 'rune platelegs (g)'
  | 'rune platelegs (t)'
  | 'rune plateskirt'
  | 'rune plateskirt (g)'
  | 'rune plateskirt (t)'
  | 'rune scimitar'
  | 'rune scimitar ornament kit (guthix)'
  | 'rune scimitar ornament kit (saradomin)'
  | 'rune scimitar ornament kit (zamorak)'
  | 'rune shield (h1)'
  | 'rune shield (h2)'
  | 'rune shield (h3)'
  | 'rune shield (h4)'
  | 'rune shield (h5)'
  | 'rune spear'
  | 'rune spear(p)'
  | 'rune spear(p+)'
  | 'rune spear(p++)'
  | 'rune sq shield'
  | 'rune sword'
  | 'rune thrownaxe'
  | 'rune trimmed set (lg)'
  | 'rune trimmed set (sk)'
  | 'rune warhammer'
  | 'runite bar'
  | 'runite bolts'
  | 'runite bolts (p)'
  | 'runite bolts (p+)'
  | 'runite bolts (p++)'
  | 'runite bolts (unf)'
  | 'runite crossbow (u)'
  | 'runite limbs'
  | 'runite ore'
  | 'sacred oil(1)'
  | 'sacred oil(2)'
  | 'sacred oil(3)'
  | 'sacred oil(4)'
  | 'sagacious spectacles'
  | 'salmon'
  | 'saltpetre'
  | 'salve graveyard teleport'
  | 'samurai boots'
  | 'samurai gloves'
  | 'samurai greaves'
  | 'samurai kasa'
  | 'samurai shirt'
  | 'sandstone (10kg)'
  | 'sandstone (1kg)'
  | 'sandstone (2kg)'
  | 'sandstone (5kg)'
  | 'sandwich lady bottom'
  | 'sandwich lady hat'
  | 'sandwich lady top'
  | 'sandworms'
  | 'sanfew serum(1)'
  | 'sanfew serum(2)'
  | 'sanfew serum(3)'
  | 'sanfew serum(4)'
  | 'sanguinesti staff (uncharged)'
  | 'santa hat'
  | 'sapphire'
  | 'sapphire amulet'
  | 'sapphire amulet (u)'
  | 'sapphire bolt tips'
  | 'sapphire bolts'
  | 'sapphire bolts (e)'
  | 'sapphire bracelet'
  | 'sapphire dragon bolts'
  | 'sapphire dragon bolts (e)'
  | 'sapphire glacialis'
  | 'sapphire necklace'
  | 'sapphire ring'
  | 'sarachnis cudgel'
  | 'saradomin armour set (lg)'
  | 'saradomin armour set (sk)'
  | 'saradomin bracers'
  | 'saradomin brew(1)'
  | 'saradomin brew(2)'
  | 'saradomin brew(3)'
  | 'saradomin brew(4)'
  | 'saradomin chaps'
  | 'saradomin cloak'
  | 'saradomin coif'
  | 'saradomin crozier'
  | "saradomin d'hide"
  | "saradomin d'hide boots"
  | "saradomin d'hide shield"
  | 'saradomin dragonhide set'
  | 'saradomin full helm'
  | 'saradomin godsword'
  | 'saradomin godsword ornament kit'
  | 'saradomin hilt'
  | 'saradomin kiteshield'
  | 'saradomin mitre'
  | 'saradomin mjolnir'
  | 'saradomin page 1'
  | 'saradomin page 2'
  | 'saradomin page 3'
  | 'saradomin page 4'
  | 'saradomin platebody'
  | 'saradomin platelegs'
  | 'saradomin plateskirt'
  | 'saradomin robe legs'
  | 'saradomin robe top'
  | 'saradomin stole'
  | 'saradomin sword'
  | "saradomin's light"
  | "saradomin's tear"
  | 'sardine'
  | 'saw'
  | 'scrambled egg'
  | 'scythe of vitur (uncharged)'
  | 'sea turtle'
  | 'seasoned sardine'
  | 'seaweed'
  | 'seaweed spore'
  | 'secateurs'
  | 'security book'
  | 'seed dibber'
  | 'seercull'
  | 'seers ring'
  | 'senntisten teleport'
  | 'serpentine helm (uncharged)'
  | 'serpentine visage'
  | 'serum 207 (1)'
  | 'serum 207 (2)'
  | 'serum 207 (3)'
  | 'serum 207 (4)'
  | 'shade robe'
  | 'shade robe top'
  | 'shaikahan bones'
  | 'shaman mask'
  | 'shantay pass'
  | 'shark'
  | 'shaving stand'
  | 'shayzien banner'
  | 'shayzien hood'
  | 'shayzien scarf'
  | 'shears'
  | 'shield left half'
  | 'shield right half'
  | 'ship ticket'
  | 'shirt'
  | 'shoe box'
  | 'short green guy'
  | 'shortbow'
  | 'shortbow (u)'
  | 'shorts'
  | 'shoulder parrot'
  | 'shrimps'
  | 'shrunk ogleroot'
  | 'sickle mould'
  | 'silk'
  | 'silver bar'
  | 'silver bolts'
  | 'silver bolts (p)'
  | 'silver bolts (p+)'
  | 'silver bolts (p++)'
  | 'silver bolts (unf)'
  | 'silver dust'
  | 'silver ore'
  | 'silver sickle'
  | 'sinew'
  | 'sinister key'
  | 'skeletal boots'
  | 'skeletal bottoms'
  | 'skeletal gloves'
  | 'skeletal helm'
  | 'skeletal top'
  | 'skeletal visage'
  | 'skewer'
  | 'skewer stick'
  | 'skills necklace'
  | 'skills necklace(4)'
  | 'skills necklace(6)'
  | 'skirt'
  | 'skull piece'
  | 'slayer bell'
  | "slayer's enchantment"
  | "slayer's respite"
  | "slayer's respite(4)"
  | "slayer's respite(m)"
  | "slayer's respite(m4)"
  | "slayer's staff"
  | 'sleeping cap'
  | 'sliced banana'
  | 'sliced mushrooms'
  | 'small box hedge'
  | 'small fishing net'
  | 'smoke battlestaff'
  | 'smoke rune'
  | 'smouldering stone'
  | 'snake hide'
  | 'snakeskin'
  | 'snakeskin bandana'
  | 'snakeskin body'
  | 'snakeskin boots'
  | 'snakeskin chaps'
  | 'snakeskin shield'
  | 'snakeskin vambraces'
  | 'snapdragon'
  | 'snapdragon potion (unf)'
  | 'snapdragon seed'
  | 'snape grass'
  | 'snape grass seed'
  | 'snowy knight'
  | 'soda ash'
  | 'soft clay'
  | 'soul rune'
  | 'spade'
  | 'spatula'
  | 'spectral sigil'
  | 'spectral spirit shield'
  | 'spice'
  | 'spicy crunchies'
  | 'spicy minced meat'
  | 'spicy sauce'
  | 'spicy tomato'
  | 'spider carcass'
  | 'spider on shaft'
  | 'spider on stick'
  | 'spiked boots'
  | 'spiked manacles'
  | 'spiky vambraces'
  | 'spinach roll'
  | 'spined body'
  | 'spined boots'
  | 'spined chaps'
  | 'spined gloves'
  | 'spined helm'
  | 'spiny helmet'
  | 'spirit shield'
  | 'split log'
  | 'splitbark body'
  | 'splitbark boots'
  | 'splitbark gauntlets'
  | 'splitbark helm'
  | 'splitbark legs'
  | 'spork'
  | 'spotted cape'
  | 'spotted kebbit fur'
  | 'spottier cape'
  | 'staff'
  | 'staff of air'
  | 'staff of balance'
  | 'staff of bob the cat'
  | 'staff of earth'
  | 'staff of fire'
  | 'staff of light'
  | 'staff of the dead'
  | 'staff of water'
  | 'stale baguette'
  | 'stamina mix(1)'
  | 'stamina mix(2)'
  | 'stamina potion(1)'
  | 'stamina potion(2)'
  | 'stamina potion(3)'
  | 'stamina potion(4)'
  | "statius's warhammer"
  | 'steam battlestaff'
  | 'steam rune'
  | 'steam staff upgrade kit'
  | 'steel 2h sword'
  | 'steel arrow'
  | 'steel arrow(p)'
  | 'steel arrow(p+)'
  | 'steel arrow(p++)'
  | 'steel arrowtips'
  | 'steel axe'
  | 'steel bar'
  | 'steel battleaxe'
  | 'steel bolts'
  | 'steel bolts (p)'
  | 'steel bolts (p+)'
  | 'steel bolts (p++)'
  | 'steel bolts (unf)'
  | 'steel boots'
  | 'steel brutal'
  | 'steel chainbody'
  | 'steel claws'
  | 'steel crossbow'
  | 'steel crossbow (u)'
  | 'steel dagger'
  | 'steel dagger(p)'
  | 'steel dagger(p+)'
  | 'steel dagger(p++)'
  | 'steel dart'
  | 'steel dart tip'
  | 'steel dart(p)'
  | 'steel dart(p+)'
  | 'steel dart(p++)'
  | 'steel dragon mask'
  | 'steel full helm'
  | 'steel full helm (g)'
  | 'steel full helm (t)'
  | 'steel gold-trimmed set (lg)'
  | 'steel gold-trimmed set (sk)'
  | 'steel halberd'
  | 'steel hasta'
  | 'steel hasta(p)'
  | 'steel hasta(p+)'
  | 'steel hasta(p++)'
  | 'steel javelin'
  | 'steel javelin heads'
  | 'steel javelin(p)'
  | 'steel javelin(p+)'
  | 'steel javelin(p++)'
  | 'steel kiteshield'
  | 'steel kiteshield (g)'
  | 'steel kiteshield (t)'
  | 'steel knife'
  | 'steel knife(p)'
  | 'steel knife(p+)'
  | 'steel knife(p++)'
  | 'steel limbs'
  | 'steel longsword'
  | 'steel mace'
  | 'steel med helm'
  | 'steel nails'
  | 'steel pickaxe'
  | 'steel platebody'
  | 'steel platebody (g)'
  | 'steel platebody (t)'
  | 'steel platelegs'
  | 'steel platelegs (g)'
  | 'steel platelegs (t)'
  | 'steel plateskirt'
  | 'steel plateskirt (g)'
  | 'steel plateskirt (t)'
  | 'steel scimitar'
  | 'steel set (lg)'
  | 'steel set (sk)'
  | 'steel spear'
  | 'steel spear(p)'
  | 'steel spear(p+)'
  | 'steel spear(p++)'
  | 'steel sq shield'
  | 'steel studs'
  | 'steel sword'
  | 'steel thrownaxe'
  | 'steel trimmed set (lg)'
  | 'steel trimmed set (sk)'
  | 'steel warhammer'
  | 'stew'
  | 'stone scarab'
  | 'stone seal'
  | 'stone statuette'
  | 'stony basalt'
  | 'strange fruit'
  | 'strawberries(5)'
  | 'strawberry'
  | 'strawberry seed'
  | 'strength amulet (t)'
  | 'strength mix(1)'
  | 'strength mix(2)'
  | 'strength potion(1)'
  | 'strength potion(2)'
  | 'strength potion(3)'
  | 'strength potion(4)'
  | 'stretched hide'
  | 'stripy feather'
  | 'stripy pirate shirt'
  | 'stronghold notes'
  | 'strung rabbit foot'
  | 'studded body'
  | 'studded body (g)'
  | 'studded body (t)'
  | 'studded chaps'
  | 'studded chaps (g)'
  | 'studded chaps (t)'
  | 'sulliuscep cap'
  | 'summer pie'
  | 'super antifire mix(1)'
  | 'super antifire mix(2)'
  | 'super antifire potion(1)'
  | 'super antifire potion(2)'
  | 'super antifire potion(3)'
  | 'super antifire potion(4)'
  | 'super attack(1)'
  | 'super attack(2)'
  | 'super attack(3)'
  | 'super attack(4)'
  | 'super combat potion(1)'
  | 'super combat potion(2)'
  | 'super combat potion(3)'
  | 'super combat potion(4)'
  | 'super def. mix(1)'
  | 'super def. mix(2)'
  | 'super defence(1)'
  | 'super defence(2)'
  | 'super defence(3)'
  | 'super defence(4)'
  | 'super energy mix(1)'
  | 'super energy mix(2)'
  | 'super energy(1)'
  | 'super energy(2)'
  | 'super energy(3)'
  | 'super energy(4)'
  | 'super kebab'
  | 'super potion set'
  | 'super restore mix(1)'
  | 'super restore mix(2)'
  | 'super restore(1)'
  | 'super restore(2)'
  | 'super restore(3)'
  | 'super restore(4)'
  | 'super str. mix(1)'
  | 'super str. mix(2)'
  | 'super strength(1)'
  | 'super strength(2)'
  | 'super strength(3)'
  | 'super strength(4)'
  | 'superantipoison(1)'
  | 'superantipoison(2)'
  | 'superantipoison(3)'
  | 'superantipoison(4)'
  | 'superattack mix(1)'
  | 'superattack mix(2)'
  | 'supercompost'
  | 'superior dragon bones'
  | 'swamp lizard'
  | 'swamp paste'
  | 'swamp tar'
  | 'swamp toad'
  | 'swamp weed'
  | 'sweetcorn'
  | 'sweetcorn seed'
  | 'swift blade'
  | 'swordfish'
  | 'tai bwo wannai teleport'
  | 'tall box hedge'
  | 'tall fancy hedge'
  | 'tan cavalier'
  | "tangled toad's legs"
  | 'tanzanite fang'
  | 'tarromin'
  | 'tarromin potion (unf)'
  | 'tarromin seed'
  | 'tarromin tar'
  | 'tatty graahk fur'
  | 'tatty kyatt fur'
  | 'tatty larupia fur'
  | 'te salt'
  | 'teacher wand'
  | 'teak armchair'
  | 'teak armour case'
  | 'teak bed'
  | 'teak bird house'
  | 'teak cape rack'
  | 'teak clock'
  | 'teak dining bench'
  | 'teak drawers'
  | 'teak dresser'
  | 'teak fancy dress box'
  | 'teak kitchen table'
  | 'teak logs'
  | 'teak magic wardrobe'
  | 'teak plank'
  | 'teak pyre logs'
  | 'teak sapling'
  | 'teak seed'
  | 'teak stock'
  | 'teak table'
  | 'teak toy box'
  | 'teak treasure chest'
  | 'teak wardrobe'
  | 'teal boots'
  | 'teal gloves'
  | 'teal hat'
  | 'teal robe bottoms'
  | 'teal robe top'
  | 'team cape i'
  | 'team cape x'
  | 'team cape zero'
  | 'team-1 cape'
  | 'team-10 cape'
  | 'team-11 cape'
  | 'team-12 cape'
  | 'team-13 cape'
  | 'team-14 cape'
  | 'team-15 cape'
  | 'team-16 cape'
  | 'team-17 cape'
  | 'team-18 cape'
  | 'team-19 cape'
  | 'team-2 cape'
  | 'team-20 cape'
  | 'team-21 cape'
  | 'team-22 cape'
  | 'team-23 cape'
  | 'team-24 cape'
  | 'team-25 cape'
  | 'team-26 cape'
  | 'team-27 cape'
  | 'team-28 cape'
  | 'team-29 cape'
  | 'team-3 cape'
  | 'team-30 cape'
  | 'team-31 cape'
  | 'team-32 cape'
  | 'team-33 cape'
  | 'team-34 cape'
  | 'team-35 cape'
  | 'team-36 cape'
  | 'team-37 cape'
  | 'team-38 cape'
  | 'team-39 cape'
  | 'team-4 cape'
  | 'team-40 cape'
  | 'team-41 cape'
  | 'team-42 cape'
  | 'team-43 cape'
  | 'team-44 cape'
  | 'team-45 cape'
  | 'team-46 cape'
  | 'team-47 cape'
  | 'team-48 cape'
  | 'team-49 cape'
  | 'team-5 cape'
  | 'team-50 cape'
  | 'team-6 cape'
  | 'team-7 cape'
  | 'team-8 cape'
  | 'team-9 cape'
  | 'teasing stick'
  | 'teleport card'
  | 'teleport to house'
  | "thammaron's sceptre (u)"
  | 'thatch spar dense'
  | 'thatch spar light'
  | 'thatch spar med'
  | 'thieving bag'
  | 'thin snail'
  | 'thin snail meat'
  | 'thorny hedge'
  | 'thread'
  | 'tiara'
  | 'tiara mould'
  | 'timber beam'
  | 'tin ore'
  | 'tinderbox'
  | 'toad batta'
  | 'toad crunchies'
  | "toad's legs"
  | 'toadflax'
  | 'toadflax potion (unf)'
  | 'toadflax seed'
  | 'toktz-ket-xil'
  | 'toktz-mej-tal'
  | 'toktz-xil-ak'
  | 'toktz-xil-ek'
  | 'toktz-xil-ul'
  | 'tomato'
  | 'tomato seed'
  | 'tomatoes(5)'
  | 'tome of fire (empty)'
  | 'tooth half of key'
  | 'top hat'
  | 'top hat & monocle'
  | 'topaz amulet'
  | 'topaz amulet (u)'
  | 'topaz bolt tips'
  | 'topaz bolts'
  | 'topaz bolts (e)'
  | 'topaz bracelet'
  | 'topaz dragon bolts'
  | 'topaz dragon bolts (e)'
  | 'topaz necklace'
  | 'topaz ring'
  | 'topiary hedge'
  | "torag's armour set"
  | "torag's hammers"
  | "torag's hammers 0"
  | "torag's helm"
  | "torag's helm 0"
  | "torag's platebody"
  | "torag's platebody 0"
  | "torag's platelegs"
  | "torag's platelegs 0"
  | 'tormented bracelet'
  | 'tormented ornament kit'
  | 'torn prayer scroll'
  | 'torstol'
  | 'torstol potion (unf)'
  | 'torstol seed'
  | 'tortoise shell'
  | 'torture ornament kit'
  | 'toxic blowpipe (empty)'
  | 'toxic staff (uncharged)'
  | 'toy cat'
  | 'toy doll'
  | 'toy doll (wound)'
  | 'toy mouse'
  | 'toy mouse (wound)'
  | 'toy soldier'
  | 'toy soldier (wound)'
  | 'trading sticks'
  | 'treasonous ring'
  | 'triangle sandwich'
  | 'tribal mask'
  | 'tribal top'
  | 'trident of the seas (full)'
  | 'trousers'
  | 'trout'
  | 'trouver parchment'
  | 'tuna'
  | 'tuna and corn'
  | 'tuna potato'
  | 'turquoise boots'
  | 'turquoise hat'
  | 'turquoise robe bottoms'
  | 'turquoise robe top'
  | 'twisted banner'
  | 'twisted blueprints'
  | 'twisted boots (t1)'
  | 'twisted boots (t2)'
  | 'twisted boots (t3)'
  | 'twisted bow'
  | 'twisted buckler'
  | 'twisted cane'
  | 'twisted coat (t1)'
  | 'twisted coat (t2)'
  | 'twisted coat (t3)'
  | 'twisted hat (t1)'
  | 'twisted hat (t2)'
  | 'twisted hat (t3)'
  | 'twisted horns'
  | 'twisted relichunter (t1) armour set'
  | 'twisted relichunter (t2) armour set'
  | 'twisted relichunter (t3) armour set'
  | 'twisted teleport scroll'
  | 'twisted trousers (t1)'
  | 'twisted trousers (t2)'
  | 'twisted trousers (t3)'
  | 'tyrannical ring'
  | 'tyras helm'
  | 'tzhaar-ket-em'
  | 'tzhaar-ket-om'
  | 'tzhaar-ket-om ornament kit'
  | 'ugthanki & onion'
  | 'ugthanki & tomato'
  | 'ugthanki kebab'
  | 'ugthanki meat'
  | 'ultracompost'
  | 'unblessed symbol'
  | 'uncharged toxic trident'
  | 'uncharged toxic trident (e)'
  | 'uncharged trident'
  | 'uncharged trident (e)'
  | 'uncooked apple pie'
  | 'uncooked berry pie'
  | 'uncooked botanical pie'
  | 'uncooked dragonfruit pie'
  | 'uncooked egg'
  | 'uncooked meat pie'
  | 'uncooked mushroom pie'
  | 'uncut diamond'
  | 'uncut dragonstone'
  | 'uncut emerald'
  | 'uncut jade'
  | 'uncut onyx'
  | 'uncut opal'
  | 'uncut red topaz'
  | 'uncut ruby'
  | 'uncut sapphire'
  | 'uncut zenyte'
  | 'unfinished broad bolts'
  | 'unfinished potion'
  | 'unfired bowl'
  | 'unfired pie dish'
  | 'unfired plant pot'
  | 'unfired pot'
  | 'unfired pot lid'
  | 'unholy blessing'
  | 'unholy book page set'
  | 'unholy symbol'
  | 'unicorn horn'
  | 'unicorn horn dust'
  | 'unlit bug lantern'
  | 'unlit torch'
  | 'unpowered orb'
  | 'unpowered symbol'
  | 'unstrung comp bow'
  | 'unstrung emblem'
  | 'unstrung heavy ballista'
  | 'unstrung light ballista'
  | 'unstrung symbol'
  | "uri's hat"
  | 'urt salt'
  | 'vampyre dust'
  | 'varrock teleport'
  | 'veg ball'
  | 'vegetable batta'
  | "verac's armour set"
  | "verac's brassard"
  | "verac's brassard 0"
  | "verac's flail"
  | "verac's flail 0"
  | "verac's helm"
  | "verac's helm 0"
  | "verac's plateskirt"
  | "verac's plateskirt 0"
  | "vesta's longsword"
  | "vesta's spear"
  | 'vial'
  | 'vial of blood'
  | 'vial of water'
  | "viggora's chainmace (u)"
  | 'villager armband'
  | 'villager hat'
  | 'villager robe'
  | 'villager sandals'
  | 'vodka'
  | 'volatile orb'
  | 'volcanic ash'
  | 'volcanic whip mix'
  | 'vyrewatch legs'
  | 'vyrewatch shoes'
  | 'vyrewatch top'
  | 'war blessing'
  | 'ward upgrade kit'
  | 'warrior helm'
  | 'warrior ring'
  | 'watchtower teleport'
  | 'water battlestaff'
  | 'water orb'
  | 'water rune'
  | 'water talisman'
  | 'water tiara'
  | 'watering can'
  | 'watermelon'
  | 'watermelon seed'
  | 'watermelon slice'
  | 'waterskin(0)'
  | 'waterskin(4)'
  | 'watson teleport'
  | 'weapon poison'
  | 'weapon poison(+)'
  | 'weapon poison(++)'
  | 'weeds'
  | 'west ardougne teleport'
  | 'whisky'
  | 'white 2h sword'
  | 'white apron'
  | 'white battleaxe'
  | 'white bead'
  | 'white beret'
  | 'white berries'
  | 'white boater'
  | 'white boots'
  | 'white cavalier'
  | 'white chainbody'
  | 'white claws'
  | 'white dagger'
  | 'white dagger(p)'
  | 'white dagger(p+)'
  | 'white dagger(p++)'
  | 'white dark bow paint'
  | 'white elegant blouse'
  | 'white elegant skirt'
  | 'white firelighter'
  | 'white flowers'
  | 'white full helm'
  | 'white gloves'
  | 'white halberd'
  | 'white headband'
  | 'white kiteshield'
  | 'white lily'
  | 'white lily seed'
  | 'white longsword'
  | 'white mace'
  | 'white magic staff'
  | 'white med helm'
  | 'white partyhat'
  | 'white platebody'
  | 'white platelegs'
  | 'white plateskirt'
  | 'white scimitar'
  | 'white sq shield'
  | 'white sword'
  | 'white toy horsey'
  | 'white unicorn mask'
  | 'white warhammer'
  | 'whiteberry seed'
  | 'wild pie'
  | 'wildblood hops'
  | 'wildblood seed'
  | 'wilderness crabs teleport'
  | 'willow bird house'
  | 'willow blackjack'
  | 'willow blackjack(d)'
  | 'willow blackjack(o)'
  | 'willow branch'
  | 'willow comp bow'
  | 'willow logs'
  | 'willow longbow'
  | 'willow longbow (u)'
  | 'willow pyre logs'
  | 'willow roots'
  | 'willow sapling'
  | 'willow seed'
  | 'willow shield'
  | 'willow shortbow'
  | 'willow shortbow (u)'
  | 'willow stock'
  | 'wine of zamorak'
  | 'wizard blizzard'
  | 'wizard boots'
  | 'wizard hat'
  | "wizard's mind bomb"
  | 'woad leaf'
  | 'woad seed'
  | 'wolf bones'
  | 'wolf cloak'
  | 'wolf mask'
  | 'wolfbone arrowtips'
  | 'wood camo legs'
  | 'wood camo top'
  | 'wood dining table'
  | 'wooden bed'
  | 'wooden bench'
  | 'wooden cat'
  | 'wooden chair'
  | 'wooden shield'
  | 'wooden shield (g)'
  | 'wooden spoon'
  | 'wooden stock'
  | 'wool'
  | 'worm batta'
  | 'worm crunchies'
  | 'worm hole'
  | 'woven top'
  | 'wrapped oomlie'
  | 'wrath rune'
  | 'wrath talisman'
  | 'wrath tiara'
  | 'wyrm bones'
  | 'wyvern bones'
  | 'wyvern visage'
  | 'xerician fabric'
  | 'xerician hat'
  | 'xerician robe'
  | 'xerician top'
  | 'yak-hide'
  | 'yak-hide armour'
  | 'yanillian hops'
  | 'yanillian seed'
  | 'yellow bead'
  | 'yellow boots'
  | 'yellow cape'
  | 'yellow dark bow paint'
  | 'yellow dye'
  | 'yellow feather'
  | 'yellow flowers'
  | 'yellow gloves'
  | 'yellow hat'
  | 'yellow partyhat'
  | 'yellow robe bottoms'
  | 'yellow robe top'
  | 'yew bird house'
  | 'yew comp bow'
  | 'yew logs'
  | 'yew longbow'
  | 'yew longbow (u)'
  | 'yew pyre logs'
  | 'yew roots'
  | 'yew sapling'
  | 'yew seed'
  | 'yew shield'
  | 'yew shortbow'
  | 'yew shortbow (u)'
  | 'yew stock'
  | 'young impling jar'
  | 'zalcano shard'
  | 'zamorak armour set (lg)'
  | 'zamorak armour set (sk)'
  | 'zamorak bracers'
  | 'zamorak brew(1)'
  | 'zamorak brew(2)'
  | 'zamorak brew(3)'
  | 'zamorak brew(4)'
  | 'zamorak chaps'
  | 'zamorak cloak'
  | 'zamorak coif'
  | 'zamorak crozier'
  | "zamorak d'hide"
  | "zamorak d'hide boots"
  | "zamorak d'hide shield"
  | 'zamorak dragonhide set'
  | 'zamorak full helm'
  | 'zamorak godsword'
  | 'zamorak godsword ornament kit'
  | 'zamorak hilt'
  | 'zamorak kiteshield'
  | 'zamorak mitre'
  | 'zamorak mix(1)'
  | 'zamorak mix(2)'
  | 'zamorak mjolnir'
  | 'zamorak monk bottom'
  | 'zamorak monk top'
  | 'zamorak page 1'
  | 'zamorak page 2'
  | 'zamorak page 3'
  | 'zamorak page 4'
  | 'zamorak platebody'
  | 'zamorak platelegs'
  | 'zamorak plateskirt'
  | 'zamorak robe legs'
  | 'zamorak robe top'
  | 'zamorak stole'
  | "zamorak's grapes"
  | 'zamorakian hasta'
  | 'zamorakian spear'
  | 'zenyte'
  | 'zenyte amulet'
  | 'zenyte amulet (u)'
  | 'zenyte bracelet'
  | 'zenyte necklace'
  | 'zenyte ring'
  | 'zenyte shard'
  | 'zogre bones'
  | 'zombie head'
  | 'zul-andra teleport'
  | "zulrah's scales"
  | "zuriel's staff";
